### ISSUE TITLE
Broken Pipe and Connection reset by peer when sending many connections

### ISSUE THREAD

**Issue by thesave** [jolie/jolie#101]
Hi, I put together this **[example](https://github.com/jolie/jolie/files/583962/example.zip)** (server+client) to showcase to students the need for coordination when accessing global variables. The client cycles 10 times over a recursive procedure, each cycle launching 100 OW calls to the server.

However, the client always terminates with either a "broken pipe" or a "connection reset by peer" error (actually, executing with `--trace` you can observe many of these errors reported by OWs).

I would like to investigate the issue but before doing so, I'd like to ask to @jolie/developers if they can give me some clue :)

Questions:
- do you think it is a Jolie-related problem or is it due to the interplay between Java and the OS (i.e., we can't fix it)?
- is the problem client- or server-side? I would say it is the server that closes the connection or disposes of the channel too soon. In that case, is [SocketListener.java](https://github.com/jolie/jolie/blob/c973725e69d95d497bd0e5740f5d8f536e856464/jolie/src/jolie/net/SocketListener.java) a good point to start investigating?

**Comment by klag** [comment]
In my installation SO Linux/Ubuntu it works with no errors.

**Comment by mawolf** [comment]
I had similar issues when doing performance testing on my macbook. Turned out to be relate to hitting the maximum number of open files (and thereby sockets).

**Comment by bmaschio** [comment]
@thesave can you provide the sample code so i can try it on window and window server?
Thanks you

**Comment by thesave** [comment]
Thanks for the quick replies!

@mawolf, you gave me a good hint :) but to me it seems that 1k connections (and not exactly concurrent) should not cause this behaviour. I recently did some stress-tests and my mac returned a `SocketException` (IRC, the exception due to exceeding the max number of open files) with more than 6k active connections (I continuously `watch`ed them with `netstat -p tcp | grep -c ESTABLISHED`). Anyhow, @mawolf do you still have the benchmarks that you mentioned, so I can test if it is the same problem that you experienced?

On a side note, I checked the pipe size of my laptop with `ulimit`, which returns `pipe size (512 bytes, -p) 1`. @klag, since it seems to work on your machine, can you issue a `ulimit -a` and report your data?

@bmaschio thank you for proposing to test it also under Windows, you can find the code at **[this link](https://github.com/jolie/jolie/files/583962/example.zip)**.

---
Slightly OT but I think it is worth sharing the knowledge. I could increase the max number of open connections under osx with commands `sudo sysctl -w kern.maxfiles=65536`, `sudo sysctl -w kern.maxfilesperproc=65536`, and `sudo ulimit -n 65536`. In linux just the last command should do the trick.

**Comment by mawolf** [comment]
What does 'ulimit -a' show?

I will try to see if I can find the benchmarks. However, I remember 1000
sockets as giving me problems as well. Sadly I don't own a mac anymore
so I cannot verify. :-/

--
Martin Wolf


On Thu, Nov 10, 2016, at 08:35 PM, thesave wrote:
> Thanks for the quick replies!
> @mawolf[1], you gave me a good hint :) but to me it seems that 1k
> connections (and not exactly concurrent) should not cause this
> behaviour. I recently did some stress-tests and my mac returned a
> SocketException (IRC, the exception due to exceeding the max number of
> open files) with more than 6k active connections (I continuously
> watched them with netstat -p tcp | grep -c ESTABLISHED). Anyhow,
> @mawolf[2] do you still have the benchmarks that you mentioned, so I
> can test if it is the same problem that you experienced?
> On a side note, I checked the pipe size of my laptop with ulimit,
> which returns pipe size (512 bytes, -p) 1. @klag[3], since it seems to
> work on your machine, can you issue a ulimit -a and report your data?
> @bmaschio[4] thank you for proposing to test it also under Windows,
> you can find the code at *this link[5]*.
>
> Slightly OT but I think it is worth sharing the knowledge. I could
> increase the max number of open connections under osx with commands
> sudo sysctl -w kern.maxfiles=65536, sudo sysctl -w
> kern.maxfilesperproc=65536, and sudo ulimit -n 65536. In linux just
> the last command should do the trick.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[6], or mute the thread[7].
>


Links:

  1. https://github.com/mawolf
  2. https://github.com/mawolf
  3. https://github.com/klag
  4. https://github.com/bmaschio
  5. https://github.com/jolie/jolie/files/583962/example.zip
  6. https://github.com/jolie/jolie/issues/101#issuecomment-259785809

**Comment by mawolf** [comment]
I just ran your example on my linux laptop without any problems. My output from ulimit -a:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63402
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63402
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by fmontesi** [comment]
Runs without problems here too (Arch Linux, Linux 4.8.4).

Keep up digging! :-)

**Comment by bmaschio** [comment]
I think I have the same problem under Windows

Microsoft Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.

C:\testJolie>jolie server.ol
100
missing: -1
98
missing: 2
100
missing: 0
100
missing: 0
100
missing: 0
100
missing: 0
97
missing: 3
99
missing: 1
45
missing: 55
99
missing: 1

Balint

**Comment by thesave** [comment]
@bmaschio if it does not show errors, it works as intended (there is no coordination on purpose :))

I also tested it under linux (I admit my laziness, I could have done it before bothering you) and everything runs smoothly.

The only relevant difference that I notice is that osx has a pipe size of 1 (i.e., 512 bytes) whilst linux shows a pipe size of 8 (i.e., 4096 bytes). 

Unfortunately I could not find a way to either increase the pipe size under osx (and see if it runs smoothly) nor to decrease the one under linux (and test if it crashes).

I'm at a dead end here. If you have any advice on this, it would be very welcome.

**Comment by mawolf** [comment]
@thesave 
I have made two small java applications that simply open sockets.
[socket-test.zip](https://github.com/jolie/jolie/files/587336/socket-test.zip)

Could you try running the jar socket-test/target/sockettest-1.0-SNAPSHOT.jar ?

Run server like `java -cp sockettest-1.0-SNAPSHOT.jar dk.martin.test.socket.Server` and client like `java -cp sockettest-1.0-SNAPSHOT.jar dk.martin.test.socket.Client 1000` where the number 1000 is the amount of sockets to create.

**Comment by mawolf** [comment]
Also, if possible. Could you run your example while executing `lsof -r 1 > log.txt` and attach the log.txt?

**Comment by bmaschio** [comment]
@mawolf 

this on windows

[LogJolieSocket.zip](https://github.com/jolie/jolie/files/589415/LogJolieSocket.zip)

**Comment by mawolf** [comment]
Thank you, @bmaschio! Now I just need to compare with @thesave. :-)

**Comment by thesave** [comment]
Sorry for the late reply and thanks for the test, @mawolf :)

I run the code both with 1k and 100k as parameters. In the first case, the output is exactly like the one posted by @bmaschio so I do not double-post it.

In case of 100k, it crashes with `java.net.SocketException: Too many open files` slightly above the 10k-th call and (surprisingly) I could not increase the number of open files with `ulimit`. On the other hand I run the 100k test with [`-XX:+MaxFDLimit`](http://www.oracle.com/technetwork/java/javase/tech/vmoptions-jsp-140102.html) and I could reach around 16.3k connections, blocking with `java.net.NoRouteToHostException: Can't assign requested address` (for what I could get, because it occupied all ephemeral ports).

In any case, I did not get the broken pipe/connection reset exception. Maybe a test that opens and closes sockets within a pool could generate it (e.g., by "stealing" an open connection or something like that). What do you think? If I have the time, I will try to fiddle with it to see if I can replicate the behaviour.

**Comment by fmontesi** [comment]
Does this still happen with the latest (git) version?

**Comment by mwallnoefer** [comment]
Let's close this, in case we may always reopen it.
