### ISSUE TITLE
Space-character marked as "Illegal Character" in paths

### ISSUE THREAD

**Issue by Tiggles** [jolie/jolie#103]
When the path to the folder containing the source code contains a space-character, this can lead to a java.net.URISyntaxException. In my case:

java.net.URISyntaxException: Illegal character in path at index 32: file:/Users/Jonas/Desktop/source code/common/type_registering.iol

I have attached a smaller version of my project, which will still give the error.

Jolie Version (built with ant):
Jolie 1.6.0 beta1  (C) 2006-2016 the Jolie team

OS:
macOS Sierra (10.12.2)

I have attached a smaller version of my project, which will still give the error.

Go into "source code" and type "jolie Service_Registry.ol"
[source code.zip](https://github.com/jolie/jolie/files/721935/source.code.zip)

**Comment by fmontesi** [comment]
Is this still a problem in the latest Jolie?

**Comment by Tiggles** [comment]
I have built from sources using ant and now have the version "Jolie 1.6.0  (C) 2006-2016 the Jolie team".

It still is an issue on both macOS Sierra (10.12.3) and Ubuntu 16.04.2 LTS.

**Comment by fmontesi** [comment]
Hi @Tiggles 

Could you apply https://jolielang.gitbooks.io/developer-guide/content/reporting-bugs.html for reproducing this thing with a minimal test that we can use? Please reopen the issue once it's done.

Cheers,
F
