### ISSUE TITLE
Flow typing

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#107]
@jolie/developers 
Hi everyone i was thinking that could be cool to introduce the concept of warning in Jolie  for typos like the following

```javascript
[op(request)(response){
   and with in the code i never use response 
}
```

or staff like this 

```javascript
 and some_variable has never been set?
 for (counter=0 ,counter< some_variable, counter++ ){
}
```

I am bashing at the wrong tree???

Balint

**Comment by fmontesi** [comment]
That should be an easy enough visitor if you don't aim at being too precise. You'll have to be lenient, in the sense that sometimes you cannot know if a variable is initialised or not.

There's a recent MSc thesis that deals with becoming pretty precise, I'll ask the author to share it.

**Comment by fmontesi** [comment]
Now tracked in #475 .
