### ISSUE TITLE
Jolie Lib need for a HTTP Client vs Output Port

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#109]
@jolie/developers 

Hi all  
In the last few days I have been trying to implement Auth2 protocol using this api provider 

https://auth0.com/

My first approach was that of defining an interface representing the API exposed by the service as Jolie interfaces 

```javascript
type tokenType:void{
  .client_id:string
  .client_secret:string
  .grant_type:string
  .code?:string
}

interface OAuthInterface {
RequestResponse:
token(tokenType)(undefined)
}
```  
And now it comes the difficult part what is the location of my service provider

```javascript
outputPort OAuthPort {
Location: "socket://35.156.229.90:443/oauth/"
Protocol: https{
  .debug= true;
  .debug.showContent = true;
  .format ="json";
  .contentType ="application/json";
  .addHeader.header[0] = "Origin";
  .addHeader.header[0].value ="http://localhost";
  .compression = false;
  .trustStoreFormat = "PKCS";
  .trustStore = "autho.p7b"
}

``` 

the value Location: "socket://35.156.229.90:443/oauth/" it comes from a  dns search
The problem is that when I am trying to call it in this way i get a 403 Forbitten

Looking at other implementation it seems that they all use HttpClients more than socket opening 
What is your though about it

Balint

**Comment by fmontesi** [comment]
Hi Balint,

I don't understand your question, probably because I'm not familiar with what auth0 needs. What is this HTTP client that you're referring to, and what should it do differently than our output port?

**Comment by fmontesi** [comment]
Hi @bmaschio 
Is this still relevant? I recall you did something with 0Auth already, so maybe it's not useful anymore? Please reopen if I'm wrong.

Cheers,
F
