### ISSUE TITLE
put the jolie version into a separate file

### ISSUE THREAD

**Issue by klag** [jolie/jolie#113]
It is very important to read the current jolie version also from a file instead only by online command jolie --version.

**Comment by fmontesi** [comment]
Why is this a bug? Is it available in other languages, e.g., Java? 

Can you elaborate on the reasons? Are you trying to manage Jolie installations in an environment without java? What limits you from storing that information in the "manager"?

**Comment by klag** [comment]
Because it is not actually possible to state the Jolie version by simply reading a file, but it is always necessary to run the command in the console.

**Comment by fmontesi** [comment]
Still sounds like a new feature, not a bug. (You've just re-stated your initial comment.) I'm removing the "bug" tag for now.

**Comment by mwallnoefer** [comment]
Now we do have also an apposite runtime service call, is that enough (commit 51b46b67a41) @klag?

**Comment by klag** [comment]
Ok for me
