### ISSUE TITLE
Jolie copydir service at file library has a bug

### ISSUE THREAD

**Issue by giaku** [jolie/jolie#117]
When I try to copy the content of a folder to another one the service crashes with the message "cannot find file". Here attached, the incriminated folder.

To reproduce the bug just try to copy  the content of target to another empty folder. It should fail with the error i mentioned above. If you then erase all the subfolders (maven-archive, generated-sources and so on) and then copy the content with just the two jars, it works perfectly.

[target.zip](https://github.com/jolie/jolie/files/1267056/target.zip)

**Comment by thesave** [comment]
It doesn't seem a Jolie bug, the code below works as expected --- no faults raised, both in case "copiedDir" is already present (empty) or created by the copyDir call. All the content of the "target" folder is correctly copied.

```Jolie
include "console.iol"
include "file.iol"

main
{
  copyDir@File( { .to = "copiedDir", .from = "target"} )( res );
  println@Console( "done: " + res )()
}
```

**Comment by fmontesi** [comment]
@giaku Can you provide a minimal example code (like the one by @thesave) that reproduces the bug in your system?

**Comment by giaku** [comment]
Hello, thanks for responding. I'm running it on ubuntu latest version on a docker virtual machine. Here my source code, as you can see I had to use a trick to avoid the error: since I don't really need those folders I delete them through a system call 'rm -rf' before copying the whole content of the folder.

Sorry I can paste just the snippet about this part:
` //Removing classes folder in target that causes an error`
`command_request4 = "rm";`
`command_request4.args[0] = "-rf";`
`command_request4.args[1] = baseWorkingDir+"hyvar/target/classes";`
`command_request4.args[2] = baseWorkingDir+"hyvar/target/generated-sources";`
`command_request4.args[3] = baseWorkingDir+"hyvar/target/maven-archiver";`
`command_request4.args[4] = baseWorkingDir+"hyvar/target/maven-status";`
`command_request4.args[5] = baseWorkingDir+"hyvar/target/archive-tmp";`
`command_request4.stdOutConsoleEnable = true;`
`command_request4.waitFor = 1;`
`exec@Exec( command_request4 )( output );`
`logFileRequest.content = "Errors: "+output.stderr;`
`saveLog@Self(logFileRequest)();`

`//Copying artifacts in output folder...`

`logFileRequest.content = "Copying artifacts in output folder...";`
`saveLog@Self(logFileRequest)();`
`copy_dir_rerquest.from = baseWorkingDir+"hyvar/target";`
`copy_dir_rerquest.to = baseWorkingDir+"output";`
`copyDir@File(copy_dir_rerquest)(result);`

**Comment by fmontesi** [comment]
@giaku Are you running the latest version of Jolie, for reference?

**Comment by giaku** [comment]
Yes, Docker container installs everything it needs at start time.
For completeness here his script regarding the Jolie installation:
        cd / && \ 
        git clone https://github.com/jolie/jolie.git && \ 
        cd jolie && \ 
	ant && ant install

**Comment by fmontesi** [comment]
@thesave can you reproduce?

**Comment by fmontesi** [comment]
Hi all,

Any news? In case this is still an issue, please apply https://jolielang.gitbooks.io/developer-guide/content/reporting-bugs.html and then reopen the issue.

Cheers,
F
