### ISSUE TITLE
Version 1.6.1 thread error

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#118]
Hi all 
After the update to 1.6.1 I have some problems with processing HTTP port call 

![image](https://user-images.githubusercontent.com/12083716/30274097-39cb99bc-96fc-11e7-8119-eec215309a20.png)

I am operating under windows 7 32 bit with java version "1.8.0_141"

I have done a downgrade to Jolie 1.6.0 and it works fine

Thanks 
Balint

**Comment by fmontesi** [comment]
Hi Balint,

Please apply https://jolielang.gitbooks.io/developer-guide/content/reporting-bugs.html and then reopen the issue.

Cheers,
F
