### ISSUE TITLE
Versione 1.6.1 error --version

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#119]
Jolie Version: 1.6.1
JVM Version: 1.8.0_151-b12
OS: Window 7

The version is not correct  jolie --version returns 1.6,0

**Comment by bmaschio** [comment]
@fmontesi @jolie/developers 
I think I found the problem

1. when you download the jar from the jolie site the file is named jolie-1.6.1.jar yet when you install it  gives you 1.6.0 when asked the version

2. If I clone the repository and install it using ant I get the correct version

I think we had some problem in the creation of the released

Thanks
Balint

**Comment by bmaschio** [comment]
@thesave 

Any Idea on this?

**Comment by thesave** [comment]
Correct, just downloaded and installed 1.6.1 from here [1] and it prints out 1.6.0.
As you said, probably it was just a typo when preparing the release. 
@fmontesi what do you think? Shall we just replace the .jar of 1.6.1 with the correct `--version` or is it better (e.g., clearer/more consistent) to create a new release with some recent fixes the correct value, e.g., a 1.6.2?

[1] https://github.com/jolie/jolie/releases

**Comment by fmontesi** [comment]
We're due for a release anyway, so I published 1.6.2. Enjoy. :-)
