### ISSUE TITLE
Aggregated port does not support referenced type??

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#120]
Hi guys 
I get this strange error any idea?
GRAVE: C:\Users\maschio\Documents\GitHub\CRM\webapp\leonardo.ol:35: error: input port HttpWebPort is trying to extend the type of
operation writeDBContact in output port DbServicePort but such operation has an unsupported type structure (type reference or type
 choice)

Thanks
Balint

**Comment by fmontesi** [comment]
Hi Balint,

Do you have a minimalistic example of this we can study?

Cheers,
F

**Comment by fmontesi** [comment]
Hi @bmaschio ,

This looks like a perfect opportunity to test our new guide: https://jolielang.gitbooks.io/developer-guide/content/reporting-bugs.html

Could you try to convert this bug to follow the guidelines? :-)

Cheers,
F

**Comment by bmaschio** [comment]
@fmontesi 
The method 1 programmer 0 Can not replicate the error must have been something silly on my part

Cheers 

Balint

**Comment by fmontesi** [comment]
It's "fixed" for now then. :-) Feel free to reopen it if it happens again.

Cheers,
F
