### ISSUE TITLE
Incoherent use of @ in valueToXml   

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#122]
@jolie/developers 

to express an xml node attributes we use the notation ```@Attributes```
Now let's imagine that we want to implement a service that  

```
type SendXmlRequest:void{
  .method: String
  .document: DocumentType
}
interface myInterface {
RequestResponse:
sendXml(SendXmlRequest)(SendXmlResponse)
}

```
where DocumentType may need to contain ```Attributes``` information, at the moment this is impossible because violates the parser constraint: would not be better using something like ```$Attributes``` or not jolie or any not Jolie key tokens

Cheers

Balint

**Comment by fmontesi** [comment]
@klag Wasn't it possible to write strings in node names in types, like `."@Attributes": AttrType` ?

Is it documented?

**Comment by klag** [comment]
I remember I fixed it

try this:
include "console.iol"

type Tex: void {
  .test: void {
      ."@Att": string
  }
}

main {
  a.test.("@Att") = "ciao";
  println@Console( a instanceof Tex )()
}

**Comment by fmontesi** [comment]
OK, then we need a test to go forward. @bmaschio : https://jolielang.gitbooks.io/developer-guide/content/reporting-bugs.html

**Comment by klag** [comment]
but it works

**Comment by fmontesi** [comment]
It doesn't for Balint apparently (forgot to say that, he told me via chat), so we need to know why.

**Comment by bmaschio** [comment]
@fmontesi @klag it works under 1.6.2 

Yet is not explained anywhere in the documentation

**Comment by klag** [comment]
Try with jolie 1.6.2

**Comment by bmaschio** [comment]
Done it works
on the documentation is missing completely any  reference closing this

**Comment by fmontesi** [comment]
Might be undocumented then, as I suspected.

I'm closing this. Feel free to open a bug or a pull request (seems rather easy to document) here: https://github.com/jolie/docs
