### ISSUE TITLE
WSDLs generated with jolie2wsdl contain wrong transport attribute

### ISSUE THREAD

**Issue by DavideRossi** [jolie/jolie#123]
As per the specs (https://www.w3.org/Submission/wsdl11soap12/) the value of the transport attribute in the binding element for HTTP is http://schemas.xmlsoap.org/soap/http, jolie2wsdl produces http://schemas.xmlsoap.org/soap/http/.
Some tools (notably Java's own wsimport) complain (rightfully so) about that.

**Comment by fmontesi** [comment]
Fixed in master.
