### ISSUE TITLE
local location definition

### ISSUE THREAD

**Issue by klag** [jolie/jolie#13]
I think it is very important to specify different local location instead of having one single reference as "local" is.

consider the case of 3 services, where A -> B, B -> C, C-> A.
If I want to deploy this architecture in a distributed way, it is very easy to manage locations outside the service code: we can use config.iol files for specifying the different locations and configure the pointers to all the services.

But if I would like to reduce the usage of ports and programming in-memory communication, these services required to be modified in the behaviour because they are not connected vertically. It is a "2D" architecture :-). Thus everywhere I put my embedder, some "local" locations created by it must be communicated to some services.

On the contrary, If we have local channel specifications we could do it in this very simple way:
- I create another microservice D which embeds A, B and C
- I define all the locations as: local://id_loc_service_A, local://id_loc_service_B, local://id_loc_service_C

In this way it is possible to manipulate deployment of local location and external locations from the outside without affecting the codes of A,B and C. This is a key point for microservice architecture management.

The structure of local locations, I suggest:

local://my_id 

Maybe we could adopt a tuple space (http://en.wikipedia.org/wiki/Tuple_space) for getting this result. In this case the tuple space should be unique for each Jolie JVM. Thus I could have nested embedded services, but all of the services which are in the same JVM use the same tuple space for communicating through local channels.

**Comment by mwallnoefer** [comment]
Very sophisticated idea ;)!

**Comment by fmontesi** [comment]
I fully agree, and actually I remember doing some work towards this by refactoring local comm channels and listeners. The last missing step is refactoring the code for the interpreter a little bit, as it has a couple of tightly coupled methods for handling the single local input port. 

If somebody wants to do this, feel free to ask. This is something that we surely need for the future. 

One language design point is that right now we can embed multiple copies of the same service using local. We'd lose this capability if we don't do something about it in the new proposal.

**Comment by fmontesi** [comment]
PS: why tuple spaces? Isn't what we have (LocalCommChannel) enough? I would just allow for separate LocalListener instances, the code is there.

**Comment by fmontesi** [comment]
Anybody interested in trying out to deal with this? It's a relatively "simple" task to start delving into the internals of the interpreter, and much of the code is already there (I refactored local for this kind of extensions a few years back).

**Comment by mawolf** [comment]
@fmontesi: What do you think about the approach where I'm implementing a register method in the Interpreter, that will add a local location name with the address of the local comm channel, to a map. This map would then be used to reference the channel and for checking whether a location exists.

**Comment by fmontesi** [comment]
Sounds good, but I wouldn't put it in Interpreter. I would rather have an external local extension (like localsockets, see its Manifest file, you'll also need to add it to build.xml and buildconfig/config.properties) where the map (is it static? I'd guess so) is held.

**Comment by fmontesi** [comment]
@mawolf and I have merged this in.
