### ISSUE TITLE
Error on concurrent execution (following documentation)

### ISSUE THREAD

**Issue by ojoaofernandes** [jolie/jolie#130]
Hi all,

First of all, congratulations for the work, Jolie is really amazing :smiley:.

I reproduced the _PercentService_  example from the _Communication Ports_ section of the documentation, however I had a problem in the following section _Processes_.

I added the _execution_ primitive and setting it as _concurrent_, however the service does not start and the following error is shown in the console.

> $ jolie Service.ol
> abr 17, 2018 1:14:46 PM jolie.lang.parse.SemanticVerifier validate
> GRAVE: Aborting: input file semantically invalid.
> abr 17, 2018 1:14:46 PM jolie.Interpreter buildOOIT
> GRAVE: /home/joao/jolie/doc/Service.ol:14: error: The first statement of the main procedure must be an input if the execution mode is not single
> 
> jolie.InterpreterException: Exiting
>         at jolie.Interpreter.buildOOIT(Interpreter.java:1268)
>         at jolie.Interpreter.init(Interpreter.java:1047)
>         at jolie.Interpreter.run(Interpreter.java:1133)
>         at jolie.Jolie.main(Jolie.java:60)

My code is exactly the same as the documentation, it was expected to work, right?

Cheers,
João Fernandes

**Comment by thesave** [comment]
Thanks @ojoaofernandes for spotting the error and to @fmontesi for the fix.
I integrated it in the documentation.

**Comment by fmontesi** [comment]
Thanks!

Case closed then.

**Comment by ojoaofernandes** [comment]
Thanks guys, it is working now.
Glad to help.

Cheers,
João Fernandes
