### ISSUE TITLE
Error on  jolie --check 

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#136]
@jolie/developers 
Jolie version 1.6.0

I have found a strange error 

```jolie
main{

  requestMatch = request.host;
  requestMatch.regex = "\\";
  find@StringUtils(requestMatch)(responseMarch);
  if (responseMarch >0){
     requestRaplaceAll = request.host;
     requestRaplaceAll.regex =  "\\";
     requestRaplaceAll.replacement = "\\\\";
     ​replaceAll@StringUtils(requestRaplaceAll)(_host)
  }else{
    _host = request.host
  };

}
```
when i run Jolie --check i get

C:\GitHub\db_connector\db_manager\db_services\Fatture_Test_handler_service\test>jolie --check test.ol
jolie.lang.parse.ParserException: C:\GitHub\db_connector\db_manager\db_services\Fatture_Test_handler_service\test\test.ol:14: error: ex
pected }. Found token type ID, token content ?replaceAll

any idea

Regards 

Balint

**Comment by fmontesi** [comment]
Works fine here, if I include "string_utils.iol" and remove the last semicolon. In any case, I cannot get your error. Have you updated Jolie? I'm closing the bug for now in the meantime.

**Comment by bmaschio** [comment]
include "string_utils.iol"

main{

  requestMatch = request.host;
  requestMatch.regex = "\\";
  find@StringUtils(requestMatch)(responseMarch);
  if (responseMarch >0){
     requestRaplaceAll = request.host;
     requestRaplaceAll.regex =  "\\";
     requestRaplaceAll.replacement = "\\\\"
     ​replaceAll@StringUtils(requestRaplaceAll)(_host)
  }else{
    _host = request.host
  }

}

**Comment by fmontesi** [comment]
2nd line of your main, you're not closing the string.

"\" -> "\\" or "\""

Cheers,
F

**Comment by fmontesi** [comment]
that happens also later, inside of the conditional (if, then branch).

**Comment by bmaschio** [comment]
![image](https://user-images.githubusercontent.com/12083716/41775284-a2d12a2e-7623-11e8-849a-30cebefa8048.png)

it gives the error line 14
also with jolie 1.6.3

**Comment by bmaschio** [comment]
include "string_utils.iol"

main{

  requestMatch = "10.101.50.74\\web";
  requestMatch.regex = "\\";
  find@StringUtils(requestMatch)(responseMarch);
  if (responseMarch >0){
     requestRaplaceAll = "10.101.50.74\\web";
     requestRaplaceAll.regex =  "\\";
     requestRaplaceAll.replacement = "\\\\";
     ​replaceAll@StringUtils(requestRaplaceAll)(_host)
  }else{
    _host = "10.101.50.74\\web"
  }

}

**Comment by fmontesi** [comment]
Still no error here (Jolie 1.6.4-git)

**Comment by bmaschio** [comment]
Ok then will wait for 1.6.4
