### ISSUE TITLE
Extra & on HTTP GET query 

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#146]
@jolie/developers 
Hi everyone 
Just playing around with HTTP GET operation I have noticed that query string has always an extra & on the end like in the example  **?term1&term2&**
It seems to cause no problems in general when calling a HTTP REST Service but i think could be confusing to the developer when debugging the content of the HTTP message

I have found the place where the issue is created  in jolie/extensions/http/src/jolie/net/HttpProtocol.java line 352 to 354
I have already solved with the following correction 

```java
			int counter =0 ; 
			int numberParameters = value.children().entrySet().size();
			for( Entry< String, ValueVector > entry : value.children().entrySet() ) {	
				for( Value v : entry.getValue() ) {
					if (counter < numberParameters -1 ) {
					headerBuilder
						.append( URLEncoder.encode( entry.getKey(), HttpUtils.URL_DECODER_ENC ) )
						.append( '=' )
						.append( URLEncoder.encode( v.strValue(), HttpUtils.URL_DECODER_ENC ) )
						.append( '&' );
					}else {
					 headerBuilder
						.append( URLEncoder.encode( entry.getKey(), HttpUtils.URL_DECODER_ENC ) )
						.append( '=' )
						.append( URLEncoder.encode( v.strValue(), HttpUtils.URL_DECODER_ENC ) );
					}
					counter++; 
				   	
				}
			}
```
If you like the change  I can commit on the master branch.

Thanks
Balint

**Comment by mwallnoefer** [comment]
I would express it a bit differently:
```
headerBuilder
	.append( URLEncoder.encode( entry.getKey(), HttpUtils.URL_DECODER_ENC ) )
	.append( '=' )
	.append( URLEncoder.encode( v.strValue(), HttpUtils.URL_DECODER_ENC ) );
if (counter < numberParameters-1)
	headerBuilder.append( '&' );
++counter;
```

**Comment by bmaschio** [comment]
yep much better like that

**Comment by fmontesi** [comment]
Thank you both! Can somebody prepare a pull request? :-)

**Comment by fmontesi** [comment]
Fixed.
