### ISSUE TITLE
JSON root values

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#15]
Hi all,

There's a new bug in JSON. If I simply return a string, it used to be:

{ "$": STRING }

Now instead it's just

STRING

which is not well-formed.

As a consequence my tool here doesn't work anymore:

http://fabriziomontesi.com/dblp/index.html

**Comment by mwallnoefer** [comment]
Yeah, I know that I have changed this during the JSON refactoring.  But I thought that it would not hurt us.
My question is: does JSON always require a whole object?

**Comment by fmontesi** [comment]
No, I changed the webpage to take the string literal instead of accessing the $ subnode and it works. 

The problem is that if we have unpredictable structures like this. Imagine having a type:

type t:string { .x?:int } 

Now where's the root? If x is there, it's in $, otherwise the message is just a string literal. So I need to write awkward code.. 

We may want your behaviour in some cases for compatibility with other frameworks maybe, but for now I'd stick to $ until we find a definite solution.

**Comment by mwallnoefer** [comment]
Ah okay, since https://tools.ietf.org/html/rfc7159#section-2 does not contradict our current behavior, it suggests only the use of arrays and objects.
