### ISSUE TITLE
Supported communication mechanism

### ISSUE THREAD

**Issue by pedramha** [jolie/jolie#163]
Hi,
I would like to know if Jolie supports Polling and pub/sub in addition to request response.
Thanks

**Comment by fmontesi** [comment]
Yes. These kinds of patterns are usually implemented by exposing an input port with some OneWay operation on which the receiver wishes to be "polled" or receive messages it subscribed for.

If you have some specific example, people are typically helpful on stackoverflow (remember to use the tag "jolie", or you risk your question going unnoticed).
