### ISSUE TITLE
SchedulerService

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#17]
This time I had a look on the source of our Java Services. The SchedulerService (javaServices/coreJavaServices/src/joliex/scheduler/SchedulerService.java) seems weird to me, since it contains plenty of commented code. I wonder if we could get rid of it, since this looks not very professional!

**Comment by klag** [comment]
I try to involve Francesco in the refactoring of the code...

**Comment by fmontesi** [comment]
That service has been unmaintained for a while. 

@klag: are we using it anywhere? If not, I'd take the occasion to refactor the api.

**Comment by klag** [comment]
We are using it in a old application. We can refactor the API, no problem.
But I would like to involve Francesco if he is available for doing it.

**Comment by fmontesi** [comment]
Absolutely, I'd like a lot to have Francesco on board too. :-)

**Comment by fmontesi** [comment]
@klag any news?

**Comment by klag** [comment]
Hi, sorry for the delay. Francesco told me that he is very busy now. I think we can go on without his contribution now. He will join us in the future. 

Do you want to refactor the SchedulerService or do you want to drop it away?

**Comment by fmontesi** [comment]
Looks like the current SchedulerService implements a couple of operations for periodic notifications that the embedder receives, in a cron-like fashion.

We should collect some use cases we want to cover (maybe from other frameworks?) and then decide on what functionalities we want it to implement. Until then, I suggest we mark it as I have no idea about the design of its interface.

Maybe we want to implement something like cron's functionalities?

I would like to see at least examples about (i) session timeouts and (ii) delayed date-based actions (like "I need to send this at 3pm").

**Comment by fmontesi** [comment]
@mwallnoefer meanwhile, if you feel like it, feel free to cut whatever comments you found, and please mark all operations as deprecated. If you want to do it, I'll mark this for Jolie 1.3.

**Comment by mwallnoefer** [comment]
Yeah, I have done my changes.
