### ISSUE TITLE
Bug in courier definition

### ISSUE THREAD

**Issue by klag** [jolie/jolie#176]
If you run the following service, just a "null" appears on the console:

`include "console.iol"
include "time.iol"

interface TestInterface {
  RequestResponse:
    test
}

interface TestInterface2 {
  RequestResponse:
    test2
}

outputPort T {
  Interfaces: TestInterface2
}

inputPort MyPort {
  Location:"socket://localhost:9000"
  Protocol: sodep
  Interfaces: TestInterface
  Aggregates: T
}

courier X {
  [ interface TestInterface2(request)( response ) ] {
    nullProcess
  }
}

main {
  test( request )( response ) {
    nullProcess
  }

}`

**Comment by fmontesi** [comment]
Will work on it.

Could you open for me a new branch in the main Jolie repo with this included as a test file in the test suite?

**Comment by klag** [comment]
done.

branch fixcourier

**Comment by fmontesi** [comment]
Fixed the null pointer exception! Your test courier was bugged, it pointed to port X which didn't exist. The code checker had a null pointer when detecting this.

**Comment by klag** [comment]
Good! I put port X because it was the way I found the bug. When the interpreter does not found the port just prints out a null on the screen.

**Comment by fmontesi** [comment]
👍
