### ISSUE TITLE
type extender does not extend undefined values

### ISSUE THREAD

**Issue by klag** [jolie/jolie#18]
If I try to extend the following interface with the Extender, the interpreter raises a NullPointerException. The problem is related to the undefined native type.
The same happens for type OpType: void { ? }

ex:
type OpType: undefined
 
interface MyInterface {
RequestResponse:
    op( OpType )( OpType )
}

**Comment by fmontesi** [comment]
We should exit with an error without a NullPointerException.

This cannot be implemented just by patching type extension right now. Type extension is an operation that takes a type and an extender and returns a type. But there is currently no way of defining the type you want. So first we'd need new syntax/semantics for something like the following:

type t:void { ? .x:int } 

Meaning "there is at least a subnode x". 

Then type extension could easily be updated I think.

**Comment by fmontesi** [comment]
@klag can you provide a quick and dirty example to fix the NullPointerException?

**Comment by fmontesi** [comment]
I fixed the NullPointerException in branch java8, the SemanticVerifier now correctly prints an error and quits.

We should discuss the issue of extending undefined types in another issue (since it's not a bug, but an enhancement). Please open it if you're interested.
