### ISSUE TITLE
Unix domain sockets

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#211]
Somehow the UNIX domain sockets do not work any more in my examples.
```
inputPort MyInput {
  Location: "localsocket://abs/s"
  Protocol: jsonrpc { .debug = true }
  Interfaces: SumInterface
}
```
Such a declaration gives me an **Unsupported communication medium: localsocket** although still mentioned in the docs: https://jolielang.gitbook.io/docs/language-tools-and-standard-library/basics/communication-ports/ports and https://jolielang.gitbook.io/docs/language-tools-and-standard-library/locations.

**Comment by fmontesi** [comment]
@bmaschio @mwallnoefer it might be that we have a problem with the POM file for localsocket, it talks about JSONRpc, bad copy-paste? :-)

https://github.com/jolie/jolie/blob/master/extensions/localsocket/pom.xml

**Comment by mwallnoefer** [comment]
Ah, sorry I have forgotten this. Please find my commit which fixes the dependencies: https://github.com/jolie/jolie/commit/e336e554fa2d9fe5bb0b4d51f58d8b5be0f836b7.

But there is still some other issue left, since the problem persists...(maybe the _localsocket_s extension source needs to be adapted somehow?)

**Comment by mwallnoefer** [comment]
The test suite states:
```
Apr. 24, 2020 11:12:01 VORM. local_server.ol
SCHWERWIEGEND: jolie.InterpreterException: /home/mdw/apps/jolie/test/extensions/private/local_server.ol:32: Local socket path not specified!
```
Why? _local_ and _localsocket_ are two independent extensions, is the parser confused that it assigns _local_ medium connections to _localsocket_?

**Comment by fmontesi** [comment]
Awesome, thanks! :-))

**Comment by mwallnoefer** [comment]
Unfortunately not completely, I had not the time to update the ticket. Everything compiles, the program starts but then the client hangs in the response loop (see attachment).

[localSocket.zip](https://github.com/jolie/jolie/files/4528722/localSocket.zip)

**Comment by mwallnoefer** [comment]
@fmontesi I have done an analysis on behalf of _strace_. The sockets are set-up and the connection gets established, but then the detection of the new data available does not seem to work any more (both the client and server get stuck in a futex loop).
So I think that there has been some compatibility breakage in the `localsocket` module against Jolie core. But I have no idea how that could be fixed, that's out of scope for me.

[localClient.out.log](https://github.com/jolie/jolie/files/4538052/localClient.out.log)
[localServer.out.log](https://github.com/jolie/jolie/files/4538053/localServer.out.log)

I will be on-line on Slack just in case you have any further question.

**Comment by fmontesi** [comment]
Confirmed (thanks for the mini-test .zip).
I'll have a look as soon as I can, this needs running the debugger.. by the way, I've pushed some .vscode settings with a launch.json that everybody can use to debug Jolie programs (just copy the setting for test.ol).

**Comment by mwallnoefer** [comment]
Any news on this one?

**Comment by fmontesi** [comment]
No but I got a bit further. The server gets stuck here:
![Screenshot_20201005_124653](https://user-images.githubusercontent.com/2077129/95070746-d9caa000-0708-11eb-8f83-f865688f6c5d.png)

So it looks like SODEP can read the first long, and then it gets stuck when reading the resource. It might be that the client is not sending correctly, it's pretty weird... If you want to have a look, you can launch vscode on the Jolie source root directory, and then launch the configuration "Debug - CustomFile". VSCode will ask you for the program to launch: you need to give it the absolute path to localClient.ol or localServer.ol. Then you can pause threads, step debug, etc. as usual.

**Comment by mwallnoefer** [comment]
I have found the problem, it lies in the _libmatthew_ library:  https://github.com/bdeneuter/matthew/pull/1

**Comment by mwallnoefer** [comment]
PR #500
