### ISSUE TITLE
IOException not raised when executed within a handler in the higher scope

### ISSUE THREAD

**Issue by klag** [jolie/jolie#212]
This code should raise a fault but it does not.

interface TestInterface {
  RequestResponse:
    testFlatStructure
}

outputPort Test {
  Location: "socketaaaaa://localhost:9000"
  Protocol: sodep
  Interfaces: TestInterface
}

init {
  install( Err => 
    scope( pippo ) {
        with( request ) {
            .afield = "ciao";
            .bfield = 10;
            .cfield = 10.0;
            .efield = "ciao";
            .ffield = true;
            .gfield = "ciao";
            .hfield = 10L
        }
        request = "ciao";
        testFlatStructure@Test( request )( response )
    })

}

main {
    throw( Err )
}

**Comment by fmontesi** [comment]
Agreed.

**Comment by fmontesi** [comment]
Should be solved now.
