### ISSUE TITLE
Bug when using internal services

### ISSUE THREAD

**Issue by klag** [jolie/jolie#218]
Added a specific test in https://github.com/jolie/jolie/tree/bugInternalService

Briefly, when using internal services all the outputPorts have also the subnode protocol created even if it is empty. It generates bugs in the Jolie code when it is necessary to pass the outputPort without specifying the location (ex: setMonitor@Runtime )

**Comment by fmontesi** [comment]
Agreed.
The code copying the output port configurations should first check whether the configuration is defined.
