### ISSUE TITLE
Jap test failing

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#221]
The test `jap.ol` currently fails on Windows. @mwallnoefer could you help me have a look?
@bmaschio, maybe this interests you as well?

The problem is that at some point in `CommandLineParser` we don't use `UriUtils.normalizeWindowsPath`.
If you use vscode, you can now simply go to the debug configurations and you will find a configuration for debugging the JAP test under Windows.

**Comment by mwallnoefer** [comment]
Fixed it (9422717d9697174d8210656f3186b9d83a10e50a), but we need to make sure that the 3 `UriUtils` helper methods get always called in the _correct_ order.

**Comment by fmontesi** [comment]
Thanks @mwallnoefer.

I wonder if we should make a convenience method that wraps the calls to these methods in that order?

**Comment by mwallnoefer** [comment]
A convenience call is not bad, but then we should also enforce its use in a consistent way. Not that we end up in the previous situation were some code places did the conversion correctly, others not.

And what about introducing the Windows normalisation directly into `UriUtils.normalizeJolieUri()`? Wouldn't that be less error-prone?
