### ISSUE TITLE
Windows: java.nio.ByteBuffer not working

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#225]
When executing Jolie's test suite on Windows the following exception is thrown:
```
operations.ol...           passed.
redirection.ol...          Exception in thread "redirector.ol-redirector.ol-SelectorThread" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at jolie.net.SocketCommChannel._isOpenImpl(SocketCommChannel.java:140)
        at jolie.util.Helpers.lockAndThen(Helpers.java:149)
        at jolie.net.SocketCommChannel.isOpenImpl(SocketCommChannel.java:181)
        at jolie.net.CommChannel.isOpen(CommChannel.java:173)
```
Is the class not available on Windows? Or at least not on Java 8?
```
PS C:\Jolie\test> java -version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)
```

**Comment by fmontesi** [comment]
Might be related to this: https://github.com/lmdbjava/lmdbjava/issues/116

**Comment by mwallnoefer** [comment]
Yes, I share the opinion that this matches exactly our problem. So it manifests itself only when we compile Jolie with Java > 8 and afterwards run on Java 8 (exactly what I did)? 

Boh, in that scenario we could also let it go, saying that if you want Java 8 you need to compile it with it.

About the Java 8 support in general: even _java.com_ continues to offer Java 8 on Windows 10, so it is definitely not dead... What do others think?

**Comment by klag** [comment]
I think that, unfortunately, we need to release Jolie for Java 8 and Jolie for Java > 8. We cannot ask to the developers to compile Jolie themselves if they want to use Java 8. When Java 8 will no longer be supported, we could say: if you want to use it, just compile jolie by yourself.

**Comment by mwallnoefer** [comment]
:neutral_face: People in the thread about lmdb suggest to introduce workaround casts like `((Buffer)buffer).clean()`. First it looks a bit ugly but second we may not guarantee to **not** introduce breakages in future code. So I am sceptical if it's worth to do so...

**Comment by fmontesi** [comment]
Mmh, I don't think it'll be necessary, as long as releases are compiled using Java 8, then all runtimes of Java >=8 should work fine.

**Comment by fmontesi** [comment]
@mwallnoefer I don't like the cast either.

Anyway, I'm just gonna compile releases using a docker image with Maven and JDK 8 until we make the switch to Java 11, just to be sure: https://github.com/jolie/release_tools/blob/master/build.sh

That hopefully works. :)

**Comment by fmontesi** [comment]
Closing this for now, let me know if you find problems with the build.sh and mkrelease scripts in release_tools.
