### ISSUE TITLE
raise a warning when using a variable named as a scope

### ISSUE THREAD

**Issue by klag** [jolie/jolie#226]
include "console.iol"

main
{
    scope( myScope ) {
        myScope.test = "this is a test"
        println@Console( myScope.test )(  )
         
    }
}

In this case the interpreter should raise a warning because it should be deprecated the usage of a variable that has the same name of a scope.

**Comment by fmontesi** [comment]
Agreed. This is also a good task for newcomers, since it's relatively self-contained.

**Comment by kicito** [comment]
maybe I could take this task?

**Comment by kicito** [comment]
please see #227.

**Comment by fmontesi** [comment]
Should be fixed by #227. @klag please check when you have a moment.

**Comment by fmontesi** [comment]
@kicito @klag By the way, I think that it'd be nice if this worked also for *nested* scopes, what do you think?

**Comment by kicito** [comment]
I think it would be a great idea!, please see #231
