### ISSUE TITLE
Can we get rid of gwt-dev.jar?

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#23]
I'm wondering whether there is a smaller library covering the API subset we're using, as this one is quite huge and currently makes up for most of the size of a Jolie installation (!).

Anyone who'd like to look into this?

**Comment by mwallnoefer** [comment]
37 MB on GWT 2.7 ;). Couldn't we make it optional - I mean just deleting it from our libs and users add their own version? We are doing the same for the JDBC drivers.

**Comment by klag** [comment]
I agree it should be optional

**Comment by fmontesi** [comment]
Excellent. I'm scheduling this for 1.3. @mwallnoefer I'll open a branch for that.

**Comment by fmontesi** [comment]
@mwallnoefer I've created the branch gwt-removal, feel free to do the change there (I'll merge it for Jolie 1.3).

**Comment by mwallnoefer** [comment]
Yeah, now I managed to understand what the problem is: we have this Jolie-GWT library joliex.gwt. * which is linked against gwt-dev.jar. So this is indeed not so easy to address, since we would not like to lose GWT support.
We would need to substitute this JAR with some kind of stub just for compile-time, and users may install their own version afterwards?
Probably we could circumvent this also by using reflection to resolve everything on runtime which requires a major reelaboration effort...

**Comment by fmontesi** [comment]
I'm doing some cleanup and it looks like removing that dependency does not make javac complain.

Can you send me a small gwt app that works now, so that I can test whether I'm making a mess by hacking some stuff out?

**Comment by mwallnoefer** [comment]
Just to clear: I have developed no GWT app (maybe someone else?) but you could try to make my test pass: https://github.com/jolie/jolie/blob/master/test/extensions/http_post.ol

**Comment by klag** [comment]
I'll try to send you a simple GWT app next week

**Comment by fmontesi** [comment]
@klag any news on the GWT app?

**Comment by fmontesi** [comment]
ping @klag (this is currently the show stopper for Jolie 1.3, I'd like to release it)

**Comment by klag** [comment]
How can we proceed? The perfect solution should be providing the GWT app source code.
Then the GWT source code should be compiled with the current release of GWT and then tested.
Is it feasible?

**Comment by fmontesi** [comment]
Well, I don't see the problem as we're not developing an automated test here yet.

If you can just share the source code of a small GWT app and tell us the command for compiling it, I think we'd be ok for this issue.

**Comment by fmontesi** [comment]
Hi all,

I went ahead and tested it with GWT 2.7. It seems that gwt-dev is not needed anymore (gwt-servlet got bigger instead), so it's now removed.
