### ISSUE TITLE
Problem while installing Jolie

### ISSUE THREAD

**Issue by fbolognesi98** [jolie/jolie#235]
When i try to install jolie 1.9 with java SE 14 and JDK 1.8 this error come up:

Illegal char <:> at index 4: file:/C:/Users/User/AppData/Local/Temp/jolie_installer_tmp80815559545284333/dist/jolie/include/types/JavaException.iol

Any suggestion?

**Comment by thesave** [comment]
Hi @fbolognesi98,

Can you please include a bit more information so we can try to help you?

- what operating system are you using? version?
- from what terminal do you launch the installer?
- from what path?
- with administrator rights?
- what version of java does run the installer? Java 8 or Java 14?

**Comment by fbolognesi98** [comment]
Yes:
-Windows 10 x64
-I use the command prompt with administrator privileges
-The path is from my documents C:Users/User/Documents/Jolie
-I think the installer run the Java 8 version (i'm not sure)

**Comment by fmontesi** [comment]
Hi all,

The current release of Jolie on the website still doesn't work with Windows, we're working on an updated release. In the meantime, you can use the installer in #220 (see bottom of the thread), that fixes a lot of problems already (but the VSCode extension doesn't work properly yet).

Best,
Fabrizio

**Comment by fbolognesi98** [comment]
Thanks @fmontesi !
Unfortunately, the installation still gives an error... 
Error: the installer could not find the launchers files. To complete the installation, try to run the installer with administrator privileges.
I've doni it several times but this error keeps coming out (even if i run the cmd prompt with administrator privileges)

**Comment by fmontesi** [comment]
Could you try this one?

https://github.com/jolie/jolie/releases/download/v1.9.1/jolie-1.9.1.jar

**Comment by fmontesi** [comment]
Closing for now, please reopen if the issue reappears.
