### ISSUE TITLE
Add automatic InternalServiceFault

### ISSUE THREAD

**Issue by klag** [jolie/jolie#236]
When a fault (or an error) is not catched within a request-response body, an automatic InternalServiceFault should be sent back to the invoker. Such a fault should be silently declared for all the operations defined in an interface, thus no TypeMismtach will be raised when it will be received.

Moreover, when an InternalServiceFault is raised, a log must be printed out on console reporting a format like this one:

<timestamp>: InternalServiceFault. Cause: <a documedebuggingntation string here>, line <XX>
where XX is the line of code which raises such a fault.

It could help in debugging easily a service

**Comment by fmontesi** [comment]
A more detailed proposal should be fleshed out but it sounds like a good addition to me. (Not sure about the best way to print on screen and the format of that value/type for the InternalServiceError, for example.)

**Comment by mwallnoefer** [comment]
This issue should have been addressed by @bmaschio 's PR #412.
