### ISSUE TITLE
Automate tests on Windows and macOS

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#238]
Anybody willing to help with checking github's documentation on how we can add testing in parallel for multiple java versions and oses to our existing github actions configuration file (link below)?

https://github.com/jolie/jolie/blob/master/.github/workflows/maven.yml

For now it tests only on Linux, and I'd like to get some better early warnings for Windows in the future.

**Comment by bmaschio** [comment]
@fmontesi 
maybe this is what we need to do 

https://www.edwardthomson.com/blog/github_actions_17_dependent_jobs.html

**Comment by fmontesi** [comment]
Something like that, yeah. I don't know if we need the setup and teardown phases, were you suggesting that? I think a matrix that tests on all OSs would be sufficient for now, but I haven't looked a lot into github actions yet.

@bmaschio can you try to edit?

**Comment by bmaschio** [comment]
@fmontesi shell I open a branch ?

**Comment by fmontesi** [comment]
@bmaschio sure! :)

**Comment by fmontesi** [comment]
Fixed by #241
