### ISSUE TITLE
Tests fail silently in mvn install

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#243]
Apparently in our transition to Maven, tests now fail silently and GitHub still think they've run ok.
See this for example: https://github.com/jolie/jolie/pull/242/checks?check_run_id=772882725#step:4:17049

@bmaschio, maybe we need a different exit status code to make mvn realise that a fault occurred?

**Comment by bmaschio** [comment]
@fmontesi I will have a look

**Comment by bmaschio** [comment]
@fmontesi  I have a proposition 

1. we add to print and println a parameter that tell to print on the error output ( system.err.println)
2. or we create an operation printlnError

in this this way   exec-maven-plugin should see the error in test jolie 
what you think

**Comment by fmontesi** [comment]
(talked with Balint and opted for an error code return)

Fixed by https://github.com/jolie/jolie/commit/f3871e218fec2f18932956d9d441d56cec4abe23
