### ISSUE TITLE
Converter test failing in Windows

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#245]
@mwallnoefer there's a converter test failing under your name (literally in the test string :-D)

https://github.com/jolie/jolie/runs/776695491#step:4:16976

Maybe it has to do with utf-8 handling?

I think we're noticing it only now because I've just fixed #243.

**Comment by fmontesi** [comment]
Ah-ha:
https://stackoverflow.com/questions/56231040/why-is-java-string-length-inconsistent-across-platforms-with-unicode-characters

Maybe we shouldn't test for length, or make sure that the test framework is launched with the appropriate -encoding?

**Comment by mwallnoefer** [comment]
> Maybe we shouldn't test for length, or make sure that the test framework is launched with the appropriate -encoding?

Exactly, on Windows we are forced to specify the `-encoding` parameter with UTF-8, otherwise the OS assumes input to be CP1252-compliant. This needs to be fixed, sorry that I have overseen this.

**Comment by mwallnoefer** [comment]
PR #340.
