### ISSUE TITLE
Optional { nullProcess } for request-response inputs

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#25]
Right now all request-response inputs require a body even though it's empty:

op( request )( response ) { nullProcess }

I'd like to be able to write this instead:

op( request )( response )

What do you think? This is in line with the recent modification to input choices.

Anybody up for this? It's a simple modification to OLParser.

**Comment by klag** [comment]
I like more 

op( request )( response ){}

**Comment by mwallnoefer** [comment]
https://github.com/mwallnoefer/jolie/commit/fc3e07b133ad0a34a198f0309e9542e2a536df3b

**Comment by fmontesi** [comment]
I agree only partially.

It's true that op(x)(y) looks more different than what we have now, but using {} makes us inconsistent with input choices, where the {} brackets are not needed.

**Comment by fmontesi** [comment]
@mwallnoefer : Instead of null, when not finding a body process please put a new NullProcessStatement( getContext() ); . This way we avoid a null, which is always nice. :-)

@klag : Any arguments for not going with consistency wrt input choices, where {} are not used (they would throw a parser exception)?

**Comment by mwallnoefer** [comment]
https://github.com/jolie/jolie/pull/28

**Comment by fmontesi** [comment]
Patch looks good now, thanks!

I'll merge it as soon as @klag lets us know if he had any particular motivation for his option.

**Comment by klag** [comment]
Ok for me. I do not have any solid motivation, it is just a personal view :-)

**Comment by fmontesi** [comment]
Fine. Matthias, please merge. :-)

@klag : I understand the gut feeling. {} gives the impression that something is actually going to happen between request and response. But hey, in the future everybody will know Jolie semantics by heart.. ;-)
