### ISSUE TITLE
Parametric procedures

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#26]
Writing Jolie code can be error-prone sometimes due to code duplication.

I propose to solve this with parametric procedures:

<pre>
define X(A, B)
{
    A = 3;
    B
}
</pre>

Where A and B can be variable paths and code, for example this is an invocation:

<pre>
p = 3;
X( p, { notify@Logger( "executed X" ) } )
</pre>

p will have value 4 after that code, because these are stateless procedures: I am *not* proposing to introduce local variables (as I think that one should use a sub service to achieve that).

Parametric procedures work in principle as our current ones, so they may recur:

<pre>
define X(A, B)
{
    A = 3;
    B;
    X( A, B )
}
</pre>

This means that they are not a simple parsing expansion, but they will need an implementation as a concrete process in the OOIT (as our current definitions, since they can also recur).

As we have parameters, we probably want to type them now otherwise we may get runtime errors. For example the following is wrong and would get us into trouble:

<pre>
define X( A )
{
   A = 3
}
</pre>

In X, A is clearly a variable so if we pass a constant instead we are making a mistake:

<pre>
X( 3 ) // this is an error because it will execute 3 = 3 inside of X
</pre>

I propose the following types: path, val, and code.

<pre>
define X( path A, val v, code C )
{
   A = v;
   C
}
</pre>

**Comment by klag** [comment]
I am a little bit confused, if we want recursive definition I think we cannot avoid to introduce local variables, that it is in contrast with the variable management approach of Jolie.

Otherwise, we could introduce a simple macro expansion into the define.

I like the idea to have macro expansion for the define, and then the possibility to define inline service.

Ex:

service Homer( req )( res ) {
      x = req + 6;
      res = x + 8
}

in the main I will call 

Homer@_( 7 )( response );

where _ should be a sort of local outputPort, or something similar

**Comment by fmontesi** [comment]
You have local "references", but not state variables.

It works by immediate expansion on call, not by creating a variable stack as in other languages.

For example when the interpreter does this:

<pre>
define X(path A)
{
     A = 3
}

main
{
    X(p)
}
</pre>

It will expand X(p) to p = 3, following the definition of X. So they are almost like a macro expansion, but the get expanded at runtime when the invocations are met, not all at once before starting execution (this is to support recursion, which cannot be implemented by expanding everything at the beginning).

Inline services cannot cover what I want to use parametric procedures for, i.e., reusable code as in my last comment in #14 . The only way to do that using services would be to implement the sending and receiving of higher-order code among services, which would be pretty resource intensive (it requires parsing and the introduction of syntax for checking that the code won't make a mess). This would be very efficient.

If you have an idea about how to do #14 in a pretty way using inline services please do share. :-)

**Comment by fmontesi** [comment]
(ps: our definitions are already recursive, so if we make them simple macro expansion we break backwards-compatibility and we need to be a bit careful)

**Comment by fmontesi** [comment]
I'm closing this for now as it seems like I can cover my use case of interest without it.
