### ISSUE TITLE
Incoherent behaviour HTTP outputPorts 

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#263]
@jolie/developers 

I was developing some unit test for an API exposed using jolier and I have noticed a curious behaviour on the HTTP outports 
My running system is 

- Jolie 1.10.0-git
- Windows 10

  and the code can be found [ErrorHttp.zip](https://github.com/jolie/jolie/files/5116783/ErrorHttp.zip)

Inside the zip file, you can find a server.ol file and client.ol the server was executed with the following command

**jolier server.ol TestPost localhost:80**

In the client, we can find two HTTP ports one for each interface exposed by the server

```jolie
outputPort Interface1Port {
    Location: "socket://localhost:80"
    Protocol: http {
        .format = "json";
        .osc.opInterface1.alias = "api/interface1/op";
        .method-> method;
        .debug = true
        
    }
   Interfaces: Interface1
}

outputPort Interface2Port {
    Location: "socket://localhost:80"
    Protocol: http {
        .format = "json";
        .osc.opInterface2.alias = "api/interface2/op";
        .method-> method;
        .debug = false
        
    }
   Interfaces: Interface2
}
```

The symptoms of the  incoherent behaviour are evident from the following image 

![httpErrorDump](https://user-images.githubusercontent.com/12083716/91025741-12e7fe80-e5fa-11ea-9642-1d358c3e97c0.png)

- The debug parameter of the second port is ignored

- The alias mapping of the second port is ignored 

Regards
Balint

**Comment by mwallnoefer** [comment]
Ok, but presumably the problem is not limited to Windows 10? You have just tested that single platform, correct?

**Comment by bmaschio** [comment]
I think so what system have you got?

**Comment by mwallnoefer** [comment]
So the issue should be reproducible on GNU/Linux or MacOS X as well.

**Comment by bmaschio** [comment]
@mwallnoefer  the code is in the Zip File

**Comment by fmontesi** [comment]
I've pushed a tentative fix to the git repo, which fixed a much smaller example on my machine. Could you test that your case works as well now?

**Comment by bmaschio** [comment]
@fmontesi  perfect for me

**Comment by fmontesi** [comment]
Awesome, thanks for checking :+1:
