### ISSUE TITLE
joliedoc requires JDK 11

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#266]
It looks like joliedoc requires JDK 11 to pass its tests now. CI was failing and I had to upgrade https://github.com/jolie/jolie/blob/master/.github/workflows/maven.yml to use JDK 11.

@klag Is this intended? Could you have a look?

I was hoping we could postpone requiring JDK 11 until Jolie 1.11, but if it's too much of a hassle we can consider switching to JDK 11 already.

**Comment by bmaschio** [comment]
@fmontesi do you want i try to run the build with java 11?

**Comment by fmontesi** [comment]
Java 11 works on CI for all OSes.

**Comment by mwallnoefer** [comment]
Sorry I am a bit puzzled: so we intend to drop the Jolie-_Java 8/9_-compatibility only for this particular tool or in general? In my opinion such a change requires a good justification. What could it be about?

**Comment by fmontesi** [comment]
No. The plan is to keep Java 8 compatibility for Jolie 1.10, so I would like this fixed.

**Comment by fmontesi** [comment]
(If possible. :-))

**Comment by klag** [comment]
It is quite strange because joliedoc is now fully implemented in Jolie.

**Comment by fmontesi** [comment]
I think it fails because of the tests (which are in Java).

**Comment by fmontesi** [comment]
Huh, looks like it's working now, closing this.
