### ISSUE TITLE
Multi User Response Header

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#267]
@jolie/committers  @jolie/contributors 

When setting multiple cookies from the server-side we may need to  set multiple times the "Set-Cookie"

[Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)

at the moment this not possible because in the method  

```java
private void send_appendResponseUserHeader( CommMessage message, StringBuilder headerBuilder ) {
.....
headerBuilder.append( entry.getKey() ).append( ": " ).append( entry.getValue().first().strValue() ) 

}
```
we always take the first value of the user-defined header 
 
I have already implemented the enhancement that looks like 

```java
			if( (responseHeaderParameters != null)
				&& (responseHeaderParameters.hasChildren( Parameters.HEADER_USER )) ) {
				for( Entry< String, ValueVector > entry : responseHeaderParameters
					.getFirstChild( Parameters.HEADER_USER ).children().entrySet() )
					for( int counter = 0; counter < entry.getValue().size(); counter++ ) {
						headerBuilder.append( entry.getKey() ).append( ": " )
							.append( entry.getValue().get( counter ).strValue() )
							.append( HttpUtils.CRLF );
					}
			}
```

Do you see any contraindication

Regards
Balint

**Comment by fmontesi** [comment]
Looks good to me, but a diff would be really helpful. :)
