### ISSUE TITLE
Internal services

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#27]
Hi all,

I'm reposting this from my original e-mail to the mailing list for Jolie 1.2. I've postponed this feature due to lack of discussion, so I'd like to rekindle that here.

# Motivation

Right now doing procedural programming in Jolie is a pain, as we do not support local variables in defined procedures. This is *intentionally* painful, as using procedures too much can make it hard to switch to a distributed implementation based on communications later on.

A procedure basically acts as a request-response invocation: we call it, and then we wait until it's done. Therefore we usually implement recursive algorithms by having a service call itself on one of its operations (e.g., [see here](http://thesave.github.io/jolie/microservices/tutorials/2015/02/03/Implementing%20QuickSort-as-a-MicroService.html)). This is a bit cumbersome sometimes and promotes bad design (algorithms should be implemented in a separate service most of the time, but creating separate services is a bother sometimes). So we need syntax sugar! All the elements are basically there, we only need to find a nice syntax and do some plumbing in the interpreter to make it work by using the mechanisms we already have. So what I would really like to have is the possibility of defining lightweight "internal" services inside of a Jolie program.

# Requirements

* Internal services should be easy to code, as in quicker than coding a fully-fledged Jolie service. We want syntax sugar. The whole reason for introducing them is to avoid the bother of defining a separate Jolie file to embed, with its interface and ports everything.
* We should also be able to have many internal services with different names, so that the programmer is left free to split operations as she sees fit.
* Finally, internal services should have the same lifecycle as a normal embedded service.

# Initial Proposal

We introduce a keyword, e.g., "service", to define internal services that works like this:

<pre>
interface SrvIface {
OneWay: op(void)
RequestResponse: op2(T)(T2)
}

service Srv {
Interfaces: SrvIface
Code: {
    [ op1() ] { ... }
    [ op2(x)(y) { ... } ]
}
}
</pre>

Srv would work as an embedded service, so this would get compiled to:

<pre>
outputPort Srv {
Interfaces: SrvIface
}

embedded {
Jolie: *internal reference to the code of the Srv* in Srv
}
</pre>

So that now we can use Srv inside of our Jolie program:

<pre>
main {
    op2@Srv( x )( y )
}
</pre>

# Discussion points

* Should Srv inherit anything from the enclosing service? Some examples follow.
* Can Srv use the output ports of the main service?
* Which state should the processes created by Srv access? Should they start with a clean state (no variables instantiated), a copy of the state of the init procedure from the main service (as do all processes started in the main service), or a copy of the state of the caller process from the main service that invokes the operation in Srv?
* Syntax: here's an alternative below. You may have other ideas, please share.

<pre>
service Srv implements SrvIface {
    [ op1() ] { ... }
    [ op2(x)(y) { ... } ]
}
</pre>

About the first three points, if we want to stay on the safe side we may start by using a clean slate (no variables instantiated at all, the internal service is completely independent), which is what I like best for now. We may also actually want internal services to have an init procedure like regular services:

<pre>
service Srv {
Interfaces: SrvIface
init {
    ...
}
main {
    [ op1() ] { ... }
    [ op2(x)(y) { ... } ]
}
}
</pre>

**Comment by klag** [comment]
I like the proposal, I just suggest to make the interface declaration as not mandatory.

As far as the questions, here my answers:
- I would allow the inheritance of the outputPort. I do not see any motivation against this.
- I think it could access just the global variables. In some cases, where there are big trees, could be useful to pass data by reference (through global) instead of values.

I like this:

service Srv implements SrvIface {
    [ op1() ] { ... }
    [ op2(x)(y) { ... } ]
}

but also this:

service Srv {
    [ op1() ] { ... }
    [ op2(x)(y) { ... } ]
}

instead of using keyword "service" we could use the keyword "private", it is just for avoiding confusion with regulare jolie service. It is just a proposal, we can discuss it.

private srv {
   [   ]
   [   ]
}

**Comment by klag** [comment]
Another possibility is that to have private operations:

[ private myop()() {
}] {}

they can be introduced in the main behavour, and they must be declared in a provate interface:

private interface MyInterface {
RequestResponse:
     myop
}

Clearly, private interfaces are not public.

**Comment by fmontesi** [comment]
I like having explicit private things but for now I'd say not to go there. That's because they already exist: you just have to declare them in an input port that only you can reach (so it's just a matter of programming a private extension if we want to go the extra mile).

**Comment by fmontesi** [comment]
I'm in favour of sharing the output ports with the binding (location, protocol) defined statically in the service but not for sharing any dynamic binding done by the invoking process.

This could mean that we should share the state of the init procedure with that of the inner service, because sometimes people initialise protocol configurations in the init procedure.

If you use the keyword "private" instead of "service" I don't see it clear that you're creating an inner service.

About not declaring interfaces, how would we then ensure type checking? Would you just have an automatic interface inferred by the interpreter where all operations have undefined types? I don't like this, because it will incite the programmer to make error-prone code. I think that we should always have types when possible.

Also, it's weird that interfaces are required for normal services but not for internal services. That means that if I export my internal service to a fully-fledged separate Jolie program, I will have to write something more than wasn't needed before.

If we want shortcuts for writing interfaces, why don't we allow them also for the main service?

**Comment by fmontesi** [comment]
@klag : any thoughts on interface declarations? If you think they can be made non-mandatory, could you make an example of how that would work?

I'd like to continue the discussion on the syntax and semantics and define a more precise development task for somebody to take.

**Comment by klag** [comment]
I think that interfaces should be provided, if you do not want types you can skip them but you need to declare the operations at least. I think the interface should be defined as all the other interfaces.

**Comment by fmontesi** [comment]
OK, that's in line with my proposal then. To sum up the current state:

# Syntax

We need to specify:

* a name for the service, which will act as an output port in the embedder to call it;
* an initialisation procedure as for regular services;
* the interfaces of the service, possibly fetching from include files just as regular services.

Example:

<pre>
service Srv { // name of the service (Srv), so the embedder can call op@Srv
Interfaces: SrvIface // interfaces
init { ... } // init procedure
main {
    [ op() ] { ... }
    [ op2(x)(y) { ... } ]
}
}
</pre>

# Semantics

The internal service:

* has access to all the output ports defined in the embedder (with the information statically defined therein, not the dynamic binding set by the caller);
* has execution { concurrent } by default; __this is convenient but a bit weird__: usually execution is set to single by default, so we should be clear about this in the documentation (big shoutbox in the middle of the page or something); for now, no way of changing the execution modality will be provided;
* is an embedded Jolie service, as if it were defined in a separate file in the same directory, the only difference being that we have some syntax sugar for defining its input port and that it is defined in the same file instead. This means that the implementation will actually load an embedded services that will behave as such (with the consequent access through Runtime and all the usual features).


Sounds good?

**Comment by klag** [comment]
I like it very much!!!!

**Comment by fmontesi** [comment]
Just fixed and merged the implementation by @mawolf, feel free to test (there's an example in test/primitives/internal_services.ol).

**Comment by fmontesi** [comment]
@thesave Could you add the keywords to the Sublime plugin ?

@jolie/developers We need to update the website for this. Anybody? :-)

**Comment by thesave** [comment]
Sure, I will take some time in the WE to test it and add it to the sublime text plugin.
Obviously if someone wants to pull-request it, be my guest :)

I will also try to make the first draft of documentation (@fmontesi is that what you mean by "website"?)

**Comment by fmontesi** [comment]
Yes, that's what I meant, thanks! :-)

**Comment by thesave** [comment]
I started tinkering with internal services ( cool :) ).

Am I right that an internal service cannot call itself by means of its OutputPort like in the example below?

    service Srv 
	{
		Interfaces: MyInterface
		main 
		{
			myOperation@Srv( req )( res ){ ... }
		}
	}

I noticed this when I tried to update my example of QuickSort with internal services.

An example of what I mean is this:

	include "console.iol"

	interface counterInterface {
	  OneWay: addOne, reset
	  RequestResponse: get, add
	}


	outputPort ToCounter {
		Interfaces: counterInterface
	}

	init
	{
	  ToCounter.location = Counter.location
	}

	main
	{
	  for (i=0, i<10, i++) {
	    addOne@Counter()
	  };
	  get@Counter()( count );
	  println@Console( count )();
	  reset@Counter();
		//
		add@Counter( 42 )();
		get@Counter()( count );
	  println@Console( count )()
	}

	service Counter 
	{
		Interfaces: counterInterface

		main 
		{
			[ add( n )() {
			  for (i=0, i < n, i++) {
			    addOne@ToCounter()
	  		}
		  } ]
			[ addOne() ]{ global.n = global.n + 1 }
			[ get()( global.n ) ]
			[ reset() ]{ global.n = 0 }
		}
	}

I would like to call Counter within Counter but the only solution I found is to create an OutputPort and pass to it the location of the internal service -- I have to do it in `init`, inside `main` it fails.

Do you think we might extend the implementation of internal services to support calls to self automatically?

Also, I updated the sublime-jolie plugin to support [internal services](https://github.com/thesave/sublime-Jolie/blob/master/internal_service.sublime-snippet), please give me a feedback before I publish the next release

**Comment by fmontesi** [comment]
I think it's just that we do not add the implicitly declared output port to the program of the embedded services in the parser. Should be easy to add. @mawolf can you have a quick look?

**Comment by mawolf** [comment]
@thesave: That is correct. The outputPort is not added to the internal service. I will have a look at it!

**Comment by thesave** [comment]
Thank you very much @mawolf :)

I am going on stress-testing internal services and I find that Aggregation is a perfect match for them.
E.g., 

    execution{ concurrent }

    type QSType: void{
    	.e*: int
    }

    interface QuicksortInterface {
      RequestResponse: quicksort( QSType )( QSType )
    }

    outputPort ToQuickSort {
    Interfaces: QuicksortInterface
    }

    inputPort ExternalInputPort {
      Location: "socket://localhost:8000"
      Protocol: http
      Aggregates: ToQuickSort
      OneWay: dummy
    }

    init
    {
      ToQuickSort.location = QuickSort.location
    }

    main
    {
      dummy()
    }

    service QuickSort {
      Interfaces: QuicksortInterface
      main {
        quicksort( req )( res ){
          if( #req.e > 1 ){
            // 1. partition the request
            pivot = #req.e / 2;
            for ( i = 0, i < #req.e, i++ ) {
              if( i != pivot ) {
                if( req.e[ i ] <= req.e[ pivot ] ) {
                  less.e[ #less.e ] << req.e[ i ]
                } else {
                greater.e[ #greater.e ] << req.e[ i ]
                }
              }
            };
            // 2. order the two partitions
            quicksort@QuickSort( less )( res );
            quicksort@QuickSort( greater )( greater );
            // merge the result
            res.e[ #res.e ] << req.e[ pivot ];
            for ( i=0, i<#greater.e, i++) {
              res.e[ #res.e ] << greater.e[ i ]
            }
          } else {
            res << req
          }
        }
      }
    }

Do you think we can make Aggregates (and Redirects and Couriers) see the OutputPorts of internal services? (and get rid of the OutputPort declaration and the `init`alisation code?

And, in general, do we want such a feature?

**Comment by fmontesi** [comment]
We definitely want that feature. To make it work, you need to declare the
input port after the service. We should implement a lazy check for input
ports, and resolve output ports later in the future (we already do similar
things for defined procedures I think).

**Comment by thesave** [comment]
Executing the service below

````
include "console.iol"
include "file.iol"

interface DummyInterface {
  OneWay: dummy
}

main { println@Console( "hello world!" )() }

service Srv 
{
	Interfaces: DummyInterface
	main { dummy() }
}
```

I get the following stack error

```
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: Aborting: input file semantically invalid.
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:85: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:85: error: unknown type for fault FileNotFound
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:111: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:133: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:127: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:83: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:83: error: unknown type for fault FileNotFound
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:97: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:92: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:124: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:84: error: unknown type for fault IOException
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:84: error: unknown type for fault FileNotFound
May 24, 2015 1:30:12 PM jolie.lang.parse.SemanticVerifier validate
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:126: error: unknown type for fault FileNotFound
May 24, 2015 1:30:12 PM jolie.Interpreter buildOOIT
SEVERE: /Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:85: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:85: error: unknown type for fault FileNotFound
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:111: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:133: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:127: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:83: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:83: error: unknown type for fault FileNotFound
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:97: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:92: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:124: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:84: error: unknown type for fault IOException
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:84: error: unknown type for fault FileNotFound
/Users/thesave/Desktop/file:/usr/lib/jolie/include/file.iol:126: error: unknown type for fault FileNotFound

Exception in thread "#Srv.ol-StarterThread-1" java.lang.NullPointerException
	at jolie.Interpreter.runCode(Interpreter.java:1075)
	at jolie.Interpreter.access$1300(Interpreter.java:102)
	at jolie.Interpreter$StarterThread.run(Interpreter.java:1159)
May 24, 2015 1:30:12 PM jolie.Interpreter logSevere
SEVERE: [tree.ol] jolie.runtime.embedding.EmbeddedServiceLoadingException: jolie.runtime.embedding.EmbeddedServiceLoadingException: jolie.InterpreterException: Exiting
	at jolie.runtime.embedding.InternalJolieServiceLoader.load(InternalJolieServiceLoader.java:69)
	at jolie.process.InitDefinitionProcess.run(InitDefinitionProcess.java:59)
	at jolie.SessionThread.runProcess(SessionThread.java:464)
	at jolie.ExecutionThread.run(ExecutionThread.java:470)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: jolie.runtime.embedding.EmbeddedServiceLoadingException: jolie.InterpreterException: Exiting
	at jolie.runtime.embedding.InternalJolieServiceLoader.load(InternalJolieServiceLoader.java:66)
	... 8 more
Caused by: jolie.InterpreterException: Exiting
	at jolie.Interpreter.buildOOIT(Interpreter.java:1242)
	at jolie.Interpreter.init(Interpreter.java:1037)
	at jolie.Interpreter.access$1100(Interpreter.java:102)
	at jolie.Interpreter$StarterThread.run(Interpreter.java:1154)

hello world!
```

The error turns out only with the internal service declaration.

Could it be a problem linked to how internal services evaluate paths of `include`s?

**Comment by fmontesi** [comment]
I believe so. @mawolf this is probably a problem with identifying the
service directory. We need to pass the same as the father service somewhere.

**Comment by fmontesi** [comment]
Reopened for handling the include file issues. I'm assigning @mawolf for now.

**Comment by mawolf** [comment]
The problem is that I don't copy over TypeDefinition, TypeDefinitionLink, and TypeDefinitionUndefined.
As soon as I have the other pull request accepted, or when I learn how to have multiple pull request on the same repo at the same time, I will make a pull request with the fix.

**Comment by fmontesi** [comment]
The other pull request is now merged. :-)

**Comment by fmontesi** [comment]
@thesave: @mawolf just committed a fix, can you check if it works now?

**Comment by thesave** [comment]
Works like a charm, thank you @mawolf :)
I am going on with testing.

**Comment by fmontesi** [comment]
Cool, I'm closing this for now then. Let's re-open it if we find other issues.
