### ISSUE TITLE
Homepage link to documentation does not work

### ISSUE THREAD

**Issue by onthebridgetonowhere** [jolie/jolie#279]
**Describe the bug**
Cannot access the docs from the link linked in the Documentation section on Github's repository page.

**To Reproduce**
1. Go to 'https://github.com/jolie/jolie#documentation-notebook_with_decorative_cover'
2. Click on 'See https://docs.jolie-lang.org/.'
3. See error

**Expected behavior**
The link should take you to the Jolie docs. Not sure if that link is still available or should be changed to [https://jolielang.gitbook.io/docs/](https://jolielang.gitbook.io/docs/)

**Comment by fmontesi** [comment]
Fixed, thank you! 👍
