### ISSUE TITLE
openapi2jolie does not generate request body and response fields in OpenAPI v3 specification files

### ISSUE THREAD

**Issue by TommasoAzz** [jolie/jolie#295]
**Describe the bug**
If we were to run openapi2jolie on a OpenAPI v3 specification file all API methods would be generated correctly in the interface, with all their request and response types also generated. By the way, no data fields are generated.

**To Reproduce**
1. Download a JSON OpenAPI file, like the [PetStore example](https://gist.githubusercontent.com/danielflower/5c5ae8a46a0a49aee508690c19b33ada/raw/b06ff4d9764b5800424f6a21a40158c35277ee65/petstore.json). Download is required because of the following issue: #296 .
2. Save it as petstore.json
3. Run openapi2jolie /path/to/petstore.json PetStore /folder/to/generate/source/into http|https
4. Look at (for example) the RequestResponse method `addPet` with request parameter addPetRequest.
**Expected behavior**
`addPetRequest` should have fields like the definition of model `Pet` at rows 950-1001 of petstore.json, instead it is empty

**Screenshots**
Just follow the steps.

**Desktop (please complete the following information):**
 - OS: Windows 10, MacOS 11.1
 - Jolie version 1.10-beta3
 - Java Version 11.0.8 on Windows, OpenJDK 1.8.0_275 on MacOS

**Additional context**
The problem of generating data fields does not apply to the generation of GET parameters.

**Comment by klag** [comment]
Hi @TommasoAzz, I run openapi2jolie for the petstore and inthe interface I have there is:

`
addPet( addPetRequest )( addPetResponse ) throws Fault500( string )  Fault405( string ) 
`
then, if I look to the types I see:
`
type Pet: void {
	.photoUrls[0,*]:string
	.name:string
	.id:long
	.category:Category
	.tags[0,*]:Tag
	.status:string
}
type addPetRequest: Pet
`
If you are running the last release, try to compile from the source code. I think it was a bug already solved.
Let me know.
