### ISSUE TITLE
openapi2jolie does not work with remote urls instead of files

### ISSUE THREAD

**Issue by TommasoAzz** [jolie/jolie#296]
**Describe the bug**
From the documentation of openapi2jolie, there is the following example:
`openapi2jolie https://petstore.swagger.io/v2/swagger.json SwaggerPetStore . https`. By the way, if we were to run it, the following exceptions would be thrown:
- on Windows: `INFO: [openapi2jolie.ol] java.io.IOException: Connessione in corso interrotta forzatamente dall'host remoto`
- on MacOS: `INFORMAZIONI: [openapi2jolie.ol] java.io.IOException: Connection reset by peer`

**To Reproduce**
1. Run `openapi2jolie https://petstore.swagger.io/v2/swagger.json SwaggerPetStore . https`

**Expected behavior**
The tool should download the file and then parse it.

**Screenshots**
From a Windows machine:
![image](https://user-images.githubusercontent.com/16544602/108065437-4ada7680-705e-11eb-8207-0b9ee2ab4263.png)

From a MacOS machine:
![image](https://user-images.githubusercontent.com/16544602/108065525-6e9dbc80-705e-11eb-9fe3-a4786b4a697b.png)

**Desktop (please complete the following information):**
- OS: Windows 10, MacOS 11.1
- Jolie version 1.10-beta3
- Java Version 11.0.8 on Windows, OpenJDK 1.8.0_275 on MacOS

**Additional context**
-

**Comment by klag** [comment]
Fixed. Find it in the repo.

**Comment by klag** [comment]
Fixed
