### ISSUE TITLE
HTTPS does not work

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#31]
Seems like the latest changes broke HTTPS, the working web server I had in website//jolie/jpsr/web/leonardo/leonardo.ol (launched by jolie/jpsr/main.ol) does not work anymore.

You can access it at https://localhost:8080/createUser.html

After we fix it let's make a test for https in the test suite before Jolie 1.3, looks like we break HTTPS now and then when we touch HTTP. It's pretty sensitive.

@mwallnoefer does it work for you?

**Comment by mwallnoefer** [comment]
Weird, since I made the changes in full accordance to HTTP.
This week I am on holidays, but next week I can look into it.

**Comment by mwallnoefer** [comment]
This is the first required change:

diff --git a/lib/jolie-ssl/src/jolie/net/ssl/SSLProtocol.java b/lib/jolie-ssl/src/jolie/net/ssl/SSLProtocol.java
index 4507402..42529c3 100644
--- a/lib/jolie-ssl/src/jolie/net/ssl/SSLProtocol.java
+++ b/lib/jolie-ssl/src/jolie/net/ssl/SSLProtocol.java
@@ -185,7 +185,7 @@ public class SSLProtocol extends SequentialCommProtocol
                throws IOException
        {
                // Set default parameters
-               String protocol = getSSLStringParameter( "protocol", "SSLv3" ),
+               String protocol = getSSLStringParameter( "protocol", "TLSv1" ),
                        keyStoreFormat = getSSLStringParameter( "keyStoreFormat", "JKS" ),
                        trustStoreFormat = getSSLStringParameter( "trustStoreFormat", "JKS" ),
                        keyStoreFile = getSSLStringParameter( "keyStore", null ),

**Comment by mwallnoefer** [comment]
Fixed by ea697477518e55a56aea6e5724ca7584305dac5d.

**Comment by fmontesi** [comment]
Great, thanks!
