### ISSUE TITLE
Broken courier behavior

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#311]
**Describe the bug**
When adding courier to a service the interpreter returns the following error
``` 
error: Main procedure for service "null" is not defined
````
**To Reproduce**
Steps to reproduce the behaviour:
unzip [Gateway.zip](https://github.com/jolie/jolie/files/6499346/Gateway.zip)
uncomment the courier section
run  
``` 
jolie Gateway.ol
````
**Expected behaviour**
Standard courier

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Jolie version 1.10.2-git
 - Java Version java 11.0.4 2019-07-16

**Note**
even with old sintax on 1.10.2 does not work it stays pending

**Comment by fmontesi** [comment]
@kicito Can you look into this?

**Comment by kicito** [comment]
I thought the fix gonna be harder :sweat_smile:.

**Comment by fmontesi** [comment]
A classic! 😜 Thanks @kicito!
