### ISSUE TITLE
Importing file with only interface definition transformed my pc in a BBQ

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#312]
**Describe the bug**
When I am trying to import from an ol file an interface  my pc get 100% CPU
```jolie
from ./RegistationInterface import RegistationInterface
```
and after a while I get 

![image](https://user-images.githubusercontent.com/12083716/118623423-86552000-b7c8-11eb-915a-c72b35a93c54.png)

**To Reproduce**
Steps to reproduce the behaviour:

1. unzip [RegistationService.zip](https://github.com/jolie/jolie/files/6499846/RegistationService.zip)
2. run  ``` jolie RegistationService.ol````

**Expected behaviour**
just able to import interface definition as use to do in 1.9.x

**Screenshots**

![image](https://user-images.githubusercontent.com/12083716/118623367-78070400-b7c8-11eb-8ed8-5c2561243593.png)

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Jolie version 1.10.2-git
 - Java Version java 11.0.4 2019-07-16

**Comment by fmontesi** [comment]
Looks like we lack some check that we might have an infinite loop?.. @kicito do you agree?

**Comment by kicito** [comment]
I added a check on #318. The issues was the token '/' shouldn't be in the module specifier

**Comment by fmontesi** [comment]
Thanks! 👍👍
