### ISSUE TITLE
Silent IndexOutOfBoundException silently block a running session

### ISSUE THREAD

**Issue by klag** [jolie/jolie#332]
**Describe the bug**
When an IndexOutOfBoundException is raised inside a session, there are no faults and the running session remains open and alive without any chance to recover it.

**To Reproduce**
added test primitives/silent-exception.ol
specific branch: https://github.com/jolie/jolie/tree/fix/silent-exception

**Comment by fmontesi** [comment]
Should be fixed by the latest PR. Closing.
