### ISSUE TITLE
Branch fix/scheduler-send-request is too big

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#337]
The branch `fix/scheduler-send-request` is too big. Please rebase it or remove it.

**Comment by fmontesi** [comment]
@klag, can this be removed?

**Comment by klag** [comment]
Try to look at it now, you should see only one file changed.

**Comment by klag** [comment]
use branch `fix/scheduler-send-request-new` instead

**Comment by fmontesi** [comment]
excellent, thank you! :)
