### ISSUE TITLE
lgtm: The variable 'result' is only assigned values of primitive type and is never 'null', but it is declared with the boxed type 'Long'.

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#341]
`public Value getTimeDiff( Value request )`
https://github.com/jolie/jolie/blob/dc4dab48a618e09f13d0b0ca76274bff63f9ed3d/javaServices/coreJavaServices/src/main/java/joliex/util/TimeService.java#L375-L376

We should fix this like in `public Value getDateDiff( Value request )`
https://github.com/jolie/jolie/blob/dc4dab48a618e09f13d0b0ca76274bff63f9ed3d/javaServices/coreJavaServices/src/main/java/joliex/util/TimeService.java#L359

Reference: https://lgtm.com/projects/g/jolie/jolie/snapshot/20b684bd4317cd7762d927e1c7cef9032e9b37e6/files/javaServices/coreJavaServices/src/main/java/joliex/util/TimeService.java?sort=name&dir=ASC&mode=heatmap#xd24c634f1a65b338:1

**Comment by mwallnoefer** [comment]
@fmontesi ?

**Comment by fmontesi** [comment]
Yes, or you can just write `long` instead of `Long`, I guess. (Both are fine by me, with a slight preference for not creating the variable.)

**Comment by mwallnoefer** [comment]
PR https://github.com/jolie/jolie/pull/347
