### ISSUE TITLE
lgtm: Variable port may be null here because of this null argument.

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#342]
`public CommChannel createCommChannel( URI uri, OutputPort port )`
https://github.com/jolie/jolie/blob/c2693e82a4cee58d0d043ae64a4cd4af4f617699/jolie/src/main/java/jolie/net/CommCore.java#L186

The port argument could be passed as `null` as shown in this occurrence:
`jolie/src/main/java/jolie/runtime/embedding/java/URIOutputPort.java:38:		CommChannel commChannel = super.targetInterpreter().commCore().createCommChannel( location, null );`

Reference: https://lgtm.com/projects/g/jolie/jolie/snapshot/20b684bd4317cd7762d927e1c7cef9032e9b37e6/files/jolie/src/main/java/jolie/net/CommCore.java?sort=name&dir=ASC&mode=heatmap

**Comment by fmontesi** [comment]
Good catch.

The signature of that method
```public CommChannel createCommChannel( URI uri, OutputPort port )```
should probably become
```public CommChannel createCommChannel( URI uri, Optional< OutputPort > port )```
and then that line should safely check whether the optional is populated or not.

**Comment by mwallnoefer** [comment]
@fmontesi?

**Comment by fmontesi** [comment]
Agreed! :) Can you transform it into a PR?

**Comment by mwallnoefer** [comment]
For sure: https://github.com/jolie/jolie/pull/346
