### ISSUE TITLE
Database connection pools

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#35]
I would like to switch to something standard for handling our database connections in DatabaseService (right now, we handle them manually), as the service needs improvements and I don't see a reason to reinvent the wheel. I had a look around but I wonder if somebody here has experience/knows what they're using in other major Java frameworks? Then we could simply go with that.

**Comment by fmontesi** [comment]
I propose we use [c3p0](http://www.mchange.com/projects/c3p0/). The port of DatabaseService should be fairly straightforward. @klag Would you like to investigate? I remember you had problems with DB connections, maybe you have test cases we can use?

**Comment by klag** [comment]
good

I did some preliminary tests and it seems to work fine.
I would like to create a specific JavaService out of the coreJavaservice called DatabaseManagerService.
I think it will help in managing version releases.

What do you think?

**Comment by fmontesi** [comment]
Sure, if just replacing the implementation of DatabaseService is not an option (why?). How would your proposal work, exactly? I mean, wrt managing "version releases" ?

**Comment by klag** [comment]
I do not like the idea to affect the releases of the Jolie interpreter with the releases of javaservices. If there will be improvements on DatabaseManagerService or bug fixes, their publication will require a new release of all the interpreter, that could be a limit.

Otherwise, I would like to have a specific project for DatabaseServiceManager and developers who want to use it, just download it and embed it out of the main Jolie interpreter release.

**Comment by fmontesi** [comment]
I fully agree, let's go with that. It will serve as an excellent use case for streamlining the development of such "Jolie Packages".

We should use a Manifest file and release the package as a JAP. How about that?
For the manifest, I would use the format already developed for JPM, see, e.g., https://github.com/jolie/jpm/blob/master/extra_server/www/cowgreet-1.0.jpmspec

I'm saying this mainly so that we start versioning the package since day one.

I'll open a repo.

**Comment by fmontesi** [comment]
There:

[https://github.com/jolie/db_connector]

We can change the name to a catchier one later if we decide to do so.. for now, simple does it. ;-)

**Comment by fmontesi** [comment]
Closed, work is going on in https://github.com/jolie/db_connector now.
