### ISSUE TITLE
jolie2java improvements and jolie2C#

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#36]
Hi all 

I have developed an upgrade for jolie2java and a  new jolie2C# tool, I need someone that would help me to test them

Thank you
Balint

**Comment by fmontesi** [comment]
Can you fork Jolie in your github user account and put the changes there? That way I think that anybody in the Jolie team could test them.

I do not have a C# installation at hand, anybody else?

@mwallnoefer can you help in testing Balint's mods to jolie2java, as you recently modified it too?

If you send me a small example, I'd be glad to test it, too.

**Comment by mwallnoefer** [comment]
Yeah, I might help.

@bmaschio would be nice if you could rebase your improvements on my changes, which got recently merged.

**Comment by bmaschio** [comment]
@mwallnoefer I have added the creation of the directories structure and relative Ant built.xml file

@fmontesi  how do i commit  the changes?

Thanks

Balint

**Comment by fmontesi** [comment]
@bmaschio: the best is that you fork Jolie (go [here](https://github.com/jolie/jolie) and click "fork" on the upper right), creating a fork in your own user account of the Jolie repository. Then, you can copy your files and commit your changes to your own Jolie repository in your user account. After that, you can create a pull request, allowing us to use the nice github web interface to review changes:
https://help.github.com/articles/creating-a-pull-request/

**Comment by bmaschio** [comment]
@fmontesi 
Upps i think i did something stupid i think i committed the changes directly on the master copy not my brantch not sure how...

**Comment by fmontesi** [comment]
@bmaschio  I think you did it right, I see them in your repository (bmaschio/jolie) not in the main jolie repository (jolie/jolie).

However, the patch is unclear, it looks like the entire file is different.

@mwallnoefer Can you help Balint in checking whether it's rebased correctly after your changes?

**Comment by mwallnoefer** [comment]
Okay, done: https://github.com/jolie/jolie/commit/860e376244ff0282a8f093cc2a263b941756ed45.

@bmaschio @fmontesi maybe I am not expert, but is this a platform independent path? 
```
String nameFile = this.directoryPath + "\\" + typeEntry.getKey() + ".java";
```

**Comment by fmontesi** [comment]
Thank you both.

No, it should use Constants.fileSeparator (from libjolie), everywhere, I
see \\ in other places, like createPackageDirectory and createBuildFile.

Also, formatExeption seems unused now and should be removed perhaps?

**Comment by mwallnoefer** [comment]
Cleanup done: 3eee2db83c77408b6bba0d640d8d7078a592d7de

**Comment by fmontesi** [comment]
Fantastic, thanks @mwallnoefer 

@bmaschio are you also coming up with a jolie2Csharp tool?

**Comment by bmaschio** [comment]
@fmontesi  I have already committed on my branch but it needs some testing, It creates only the classes but not project structure because Microsoft in its infinite wisdom does not provide any information on their project definition file ;) Is Bergar still interested?

**Comment by mwallnoefer** [comment]
Any news here?

**Comment by bmaschio** [comment]
@fmontesi @mwallnoefer Not quite sure hot to commit it where about

**Comment by mwallnoefer** [comment]
@bmaschio maybe push it in a separate branch in your repo, so I can give you more advices about how to integrate it.

**Comment by fmontesi** [comment]
News about this @mwallnoefer @bmaschio ?

**Comment by bmaschio** [comment]
I need some to test it I don't have a .net version to test it on

**Comment by fmontesi** [comment]
Hi both,

Closing this for now, since it's more related to a new project. Please feel free to renew it on the Mailing List in case you'd like to find some help.

Cheers,
Fabrizio
