### ISSUE TITLE
openapi2jolie not working

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/jolie#366]
**Describe the bug**
If you launch the tool it said
Protocol not supported

**To Reproduce**
openapi2jolie <file-openapi> <desired service name> . http

**Expected behavior**
Create two files
The include e the jolie service

**Screenshots**
---

**Desktop (please complete the following information):**
 - OS: Linux]
 - Jolie version 1.10.5
 - Java Version 11.0.11

** Proposed solution
The problem arise in the check of the number of parameters.
I successfully tried the following solution (attached file).

[openapi2jolie.txt](https://github.com/jolie/jolie/files/7582175/openapi2jolie.txt)

**Comment by mwallnoefer** [comment]
Patch to merge: https://github.com/jolie/jolie/pull/505/commits/f53e42e4edd70c87726499e0f4be81ee2f8ca1f6
