### ISSUE TITLE
openapi2jolie - error check in operations generated

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/jolie#368]
**Describe the bug**
Generating the code for the different supported operations,
the code for checking the result status, check for a default variable instead of "default"

**To Reproduce**
See issue #367
Verify the start of every operation generated.

**Expected behavior**
default -> "default"

**Screenshots**
---

**Desktop (please complete the following information):**
 - OS: Linux
 - Jolie version 1.10.5
 - Java Version jdk 11

**Additional context**

**Comment by mwallnoefer** [comment]
Fixed by the following commit proposal: https://github.com/jolie/jolie/pull/505/commits/c2c1e45901a8cdf4c3dc51e7f07cdcfbc43145bc
