### ISSUE TITLE
Behavior difference Jolie2Wsdl 

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#37]
Hello everyone

During a Jolie training session i have notice a difference between the Jolie2Wsdl suggested use and the real command parser
This is the suggested use 

jolie2wsdl [ -i include_file_path ] filename.ol soap_input_port_name 
[ output_file ]

C:\Vincent Examples\TestVersion1.2.1\TestWSDL>jolie2wsdl main_test_wsdl.ol TestInterfaceSoapInputPort test.wsdl
Starting conversion...
null
apr 24, 2015 9:22:38 AM joliex.wsdl.WSDLDocCreator ConvertDocument
GRAVE: null
java.lang.NullPointerException
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at joliex.wsdl.WSDLDocCreator.initWsdl(WSDLDocCreator.java:121)
        at joliex.wsdl.WSDLDocCreator.ConvertDocument(WSDLDocCreator.java:138)
        at joliex.wsdl.Jolie2Wsdl.main(Jolie2Wsdl.java:41)

Success: WSDL document generated!

  but no file was generated

Instead using the following command form it seems to work fine
C:\Vincent Examples\TestVersion1.2.1\TestWSDL>jolie2wsdl  --tns nameSpaceWsdl --
pN TestInterfaceSoapInputPort --addr http://localhost:10000 --oF TestService.wsd
l main_test_wsdl.ol

This is due by the following command parser implementation for Jolie2wsdl 

 private static class JolieDummyArgumentHandler implements CommandLineParser.ArgumentHandler {

        private String portName;
        private String tns;
        private String address;
        private String outputFile;
            
        public int onUnrecognizedArgument(List< String> argumentsList, int index)
                throws CommandLineException {
            if ("--tns".equals(argumentsList.get(index))) {
                index++;
                tns = argumentsList.get(index);
            } else if ("--pN".equals(argumentsList.get(index))) {
                index++;
                portName = argumentsList.get(index);
            } else if ("--addr".equals(argumentsList.get(index))) {
                index++;
                address = argumentsList.get(index);
            } else if ("--oF".equals(argumentsList.get(index))) {
                index++;
                outputFile = argumentsList.get(index);
            } else {
                throw new CommandLineException("Unrecognized command line option: " + argumentsList.get(index));
            }

            return index;
        }
    }

If you want i can modify the documentation or work on the parser itself

Tnks

Balint

**Comment by fmontesi** [comment]
@klag @mwallnoefer If I remember correctly, this is because the --help implementation of jolie2wsdl is wrong (and the website docs). Can you help in patching it?

I think that some parameters could be improved. --tns could be --namespace, --addr and --pN are a bit unintuitive, and --oF is usually -o in standard tools AFAIK.

What do you think?

**Comment by mwallnoefer** [comment]
@fmontesi @klag I do not remember anything about the --help implementation of jolie2wsdl, maybe Claudio?

@bmaschio The rename proposals of Fabrizio sound good to me, feel free to help us there.

**Comment by bmaschio** [comment]
@fmontesi @mwallnoefer That is good for me i will commit this afternoon on my branch

**Comment by bmaschio** [comment]
@fmontesi @mwallnoefer  Now on my pc it looks like this what do you think


C:\Vincent Examples\TestVersion1.2.1\TestWSDL>jolie2wsdl --namespace testwsdl ---portNameTestInterfaceSoapInputPort --portAddr http://localhost:10000 --outFile
TestWsdl.wsdl main_test_wsdl.ol
Starting conversion...
Success: WSDL document generated!

**Comment by mwallnoefer** [comment]
Ah, I have overseen this. These parameter proposals look good to me.

@fmontesi ?

**Comment by fmontesi** [comment]
---portName should be --portName (there's an extra dash?)

All the rest is good. Why --outFile instead of -o as is standard? To be consistent in our own params?

**Comment by bmaschio** [comment]
@fmontesi  ok for -o for output

**Comment by bmaschio** [comment]
@fmontesi @mwallnoefer  

done commited

**Comment by mwallnoefer** [comment]
Patch tested and committed: 7c8221382afe9af98d4f816caca97ffe7a5cbf2a

**Comment by fmontesi** [comment]
Fantastic, thank you all. Is the documentation on the website up to date with this?

**Comment by mwallnoefer** [comment]
No, not yet: http://docs.jolie-lang.org/#!documentation/web_services/jolie2wsdl.html

@bmaschio would you like to try updating the MD file? It is not so hard...

**Comment by bmaschio** [comment]
@mwallnoefer  MD as manual online?

**Comment by mwallnoefer** [comment]
Ah, sorry I have forgotten to answer. These are the files which need to be adjusted:

https://github.com/jolie/website/blob/master/docs/documentation/web_services/jolie2wsdl.md
https://github.com/jolie/website/blob/master/docs/documentation/web_services/syntax/syntax_jolie2wsdl.ol
https://github.com/jolie/website/blob/master/docs/documentation/web_services/web_services.md (bottom)

GitHub offers this cool editing feature with the pencil on the top right corner. This automatically creates you a personal branch containing your modifications. These can then be merged easily.

**Comment by bmaschio** [comment]
@mwallnoefer no problem I will do it tonight

**Comment by fmontesi** [comment]
Looks fixed by a recent commit by @bmaschio in the website repo.
