### ISSUE TITLE
Parser : error generated because can't import include file from jap file 

### ISSUE THREAD

**Issue by SuperMauro1966** [jolie/jolie#370]
**Describe the bug**
The parser (jolie --check <name file>) cannot import from a jap file.
So the inclusion directive
include "../jung.microservices.registry/public/interfaces/JungRegistryInterface.iol"

( jung.microservice.registry is a jap file inside the lib folder)

generate the follow error

error: File not found: ../jung.microservices.registry/public/interfaces/JungRegistryInterface.iol. Found token type STRING, token content ../jung.microservices.registry/public/interfaces/JungRegistryInterface.iol

This is a serious problem because the parser stop and do not continue the checking process.

In these cases, actually, we can find errors only running the code, but if this code is an embedded service this could drive to a difficult debug session. 

**To Reproduce**
1. create one include to a file contained in a jap file inside the folder lib
2. write some code, with a faulty line, at less
3. launch jolie --check <name file>
4. See that only the include error is reported

**Expected behavior**
The parser must be able to include the file from a jap package and continue the static lexical analysis of the code.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Jolie version 1.10.5
 - Java Version openjdk 11.0.13

**Additional context**

**Comment by fmontesi** [comment]
Isn't that supposed to be like include "jap:.." ? Or are you including directly from within the same jap?

**Comment by mwallnoefer** [comment]
I guess this issue could have been fixed meanwhile by the introduction of the new modules feature `from ... import ...`.

If this was not the case, please reopen.
