### ISSUE TITLE
Moving method from match from UriTemplates to jolie-uri

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#379]
@fmontesi 

As from our conversation on discord we need to move the method match from 

[UriTemplates](https://github.com/jolie/jolie/blob/master/javaServices/coreJavaServices/src/main/java/joliex/util/UriTemplates.java)

to

jolie-uri 

But in the usual place, I can not find it

![image](https://user-images.githubusercontent.com/12083716/163153773-bf6d41a0-4325-48a8-a352-1d72d6a96d78.png)

seeking advice

**Comment by fmontesi** [comment]
I guess this is closed judging from your last pr.
