### ISSUE TITLE
Jolie Web Services acquired by NetBeans 

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#38]
Hi all

It is me again , being the usual pain , I was going to write a post on how to integrate Jolie Microservices in Java Program. So I thought to have a go with importing Jolie WebServices Using NetBeans 8.0.1 
And this is how i went about it

1) Create a simple Java Program
2) Use the WebService Client to digest the WSDL generated by Jolie2WSDL
![image](https://cloud.githubusercontent.com/assets/12083716/7347542/e277feee-ece9-11e4-82b5-8ea412cc1812.png)
3) Drag the WebService operation  testOperation into the java class this creates the following method 

    private static void testOperation(java.lang.String field1, java.lang.String field2, javax.xml.ws.Holder<java.lang.String> field3, javax.xml.ws.Holder<java.lang.String> field4) {
	TestInterfaceSoapInputPortService service = new wsdl.namespacewsdl.TestInterfaceSoapInputPortService();
	TestInterfaceSoapInputPort port = service.getTestInterfaceSoapInputPortServicePort();
	port.testOperation(field1, field2, field3, field4);
    }

From a Jolie interface that looks like this  
type TestOperationRequest:void{
	.field1: string
	.field2: string
}

type TestOperationResponse:void{
	.field3: string	
	.field4: string
}

interface TestInterface {
  RequestResponse: 
  testOperation (TestOperationRequest)(TestOperationResponse)
}

Strait away i noticed some problems  the signature of the java rapping method looks like not having response type

private static void testOperation(java.lang.String field1, java.lang.String field2, javax.xml.ws.Holder<java.lang.String> field3, javax.xml.ws.Holder<java.lang.String> field4)

Both input and output structures are flatten and passed as parameters of the method 

4) moving on i have tried use anyhow the generated method within my main method

	javax.xml.ws.Holder<java.lang.String> field3 = new Holder<>();
        javax.xml.ws.Holder<java.lang.String> field4 = new Holder<>();
	testOperation("a", "b", field3, field4);

5) running the code I get

Exception in thread "main" com.sun.xml.internal.ws.streaming.XMLStreamReaderException: unexpected XML tag. expected: {nameSpaceWsdl.xsd}testOperationResponse but found: {null}testOperationResponse
	at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.verifyTag(XMLStreamReaderUtil.java:203)
	at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.verifyTag(XMLStreamReaderUtil.java:211)
	at com.sun.xml.internal.ws.client.sei.ResponseBuilder$DocLit.readResponse(ResponseBuilder.java:538)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:110)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:135)
	at com.sun.proxy.$Proxy31.testOperation(Unknown Source)
	at wsdltest.WSDLTest.testOperation(WSDLTest.java:36)
	at wsdltest.WSDLTest.main(WSDLTest.java:29)
Java Result: 1

Where the jolie port output is the following

<?xml version="1.0" encoding="utf-8" ?><SOAP-ENV:Envelope xmlns:SOAPENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema
" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Body><testOper
ationResponse><field3 xsi:type="xsd:string">a</field3><field4 xsi:type="xsd:stri
ng">b</field4></testOperationResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

6) with the option .dropRootValue = true; the situation does not change

Exception in thread "main" com.sun.xml.internal.ws.streaming.XMLStreamReaderException: unexpected XML tag. expected: {nameSpaceWsdl.xsd}testOperationResponse but found: {null}testOperationResponse
	at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.verifyTag(XMLStreamReaderUtil.java:203)
	at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.verifyTag(XMLStreamReaderUtil.java:211)
	at com.sun.xml.internal.ws.client.sei.ResponseBuilder$DocLit.readResponse(ResponseBuilder.java:538)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:110)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:78)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:135)
	at com.sun.proxy.$Proxy31.testOperation(Unknown Source)
	at wsdltest.WSDLTest.testOperation(WSDLTest.java:36)
	at wsdltest.WSDLTest.main(WSDLTest.java:29)
Java Result: 1

7) Now to test if was my procedure to be wrong I tested it against a standard WebService the we all know  http://www.webservicex.net/globalweather.asmx?WSDL

8) now the generated method looks more like what i would expect 

  private static String getCitiesByCountry(java.lang.String countryName) {
	net.webservicex.GlobalWeather service = new net.webservicex.GlobalWeather();
	net.webservicex.GlobalWeatherSoap port = service.getGlobalWeatherSoap12();
	return port.getCitiesByCountry(countryName);
    }

that looks more like the wsdl definition

![image](https://cloud.githubusercontent.com/assets/12083716/7348271/649e61dc-ecf0-11e4-8aab-e2110055935b.png)

9) if i call the method i get a list of data as I expect

I was wandering if any of you has experienced this before or it is a problem on how jolie answer  to a soap call 

I must say we had the same problem when trying a similar procedure under .NET, but at the time we thought to be a problem with .NET

Thank you
Balint

**Comment by fmontesi** [comment]
Hi Balint,

Really interesting. Can you try to replicate the GetCitiesByCountry operation from that web service in Jolie, and tell us the output wsdl that you get out of jolie2wsdl? Also, I can't see your SOAP messages, you have to use the pre tag like this:

    <pre>
    your code here...
    </pre>

**Comment by bmaschio** [comment]
@fmontesi 
Yes i do it straight away i will post all the code and resulting WSDL

**Comment by bmaschio** [comment]
@fmontesi 

Here we are I have replicated the operation exported by the GetWeatherSevice
Please note I have defined the Jolie operation type with the same name of the MessageType in the original WSDL
```xml
/*<
<s:element name="GetCitiesByCountry">
<s:complexType>
<s:sequence>
<s:element minOccurs="0" maxOccurs="1" name="CountryName" type="s:string"/>
</s:sequence>
</s:complexType>
</s:element>
<s:element name="GetCitiesByCountryResponse">
<s:complexType>
<s:sequence>
<s:element minOccurs="0" maxOccurs="1" name="GetCitiesByCountryResult" type="s:string"/>
</s:sequence>
</s:complexType>
</s:element>

*/


type GetCitiesByCountry:void{
	.CountryName?:string
}


type GetCitiesByCountryResponse:void{
	.GetCitiesByCountryResult?:string
}
/*
<wsdl:message name="GetCitiesByCountrySoapIn">
<wsdl:part name="parameters" element="tns:GetCitiesByCountry"/>
</wsdl:message>
<wsdl:message name="GetCitiesByCountrySoapOut">
<wsdl:part name="parameters" element="tns:GetCitiesByCountryResponse"/>
</wsdl:message>
*/

type GetCitiesByCountrySoapIn:void{
	.parameters: GetCitiesByCountry
}

type GetCitiesByCountrySoapOut:void{
	.parameters: GetCitiesByCountryResponse
}



interface JolieWeatherInterface {
  RequestResponse: 
  GetCitiesByCountry (GetCitiesByCountrySoapIn)(GetCitiesByCountrySoapOut)
}
```
then I have tried to regenerate the classes in NetBeans amd i get the following error)


![image](https://cloud.githubusercontent.com/assets/12083716/7349451/6f769152-ecf9-11e4-890e-1a54388ffac6.png)

the resulting WSDL it is
```xml
<?xml version="1.0" encoding="UTF-8"?>
-<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="null.wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd1="null.xsd" targetNamespace="null.wsdl"> -<wsdl:types> -<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="null.xsd" xmlns:sch="null.xsd">-<xs:complexType name="GetCitiesByCountry">-<xs:sequence><xs:element name="CountryName" type="xs:string" minOccurs="0" maxOccurs="1"/></xs:sequence></xs:complexType>-<xs:element name="GetCitiesByCountry">-<xs:complexType>-<xs:sequence><xs:element name="parameters" type="sch:GetCitiesByCountry" minOccurs="1" maxOccurs="1"/></xs:sequence></xs:complexType></xs:element>-<xs:complexType name="GetCitiesByCountryResponse">-<xs:sequence><xs:element name="GetCitiesByCountryResult" type="xs:string" minOccurs="0" maxOccurs="1"/></xs:sequence></xs:complexType>-<xs:element name="GetCitiesByCountryResponse">-<xs:complexType>-<xs:sequence><xs:element name="parameters" type="sch:GetCitiesByCountryResponse" minOccurs="1" maxOccurs="1"/></xs:sequence></xs:complexType></xs:element></xs:schema> </wsdl:types> -<wsdl:message name="GetCitiesByCountrySoapOut"> <wsdl:part name="body" element="xsd1:GetCitiesByCountryResponse"/> </wsdl:message> -<wsdl:message name="GetCitiesByCountrySoapIn"> <wsdl:part name="body" element="xsd1:GetCitiesByCountry"/> </wsdl:message> -<wsdl:portType name="TestInterfaceSoapInputPort"> -<wsdl:operation name="GetCitiesByCountry"> <wsdl:input message="tns:GetCitiesByCountrySoapIn"/> <wsdl:output message="tns:GetCitiesByCountrySoapOut"/> </wsdl:operation> </wsdl:portType> -<wsdl:binding name="TestInterfaceSoapInputPortSOAPBinding" type="tns:TestInterfaceSoapInputPort"> <soap:binding transport="http://schemas.xmlsoap.org/soap/http/" style="document"/> -<wsdl:operation name="GetCitiesByCountry"> <soap:operation style="document" soapAction="GetCitiesByCountry"/> -<wsdl:input> <soap:body use="literal"/> </wsdl:input> -<wsdl:output> <soap:body use="literal"/> </wsdl:output> </wsdl:operation> </wsdl:binding> -<wsdl:service name="TestInterfaceSoapInputPortService"> -<wsdl:port name="TestInterfaceSoapInputPortServicePort" binding="tns:TestInterfaceSoapInputPortSOAPBinding"> <soap:address location="http://localhost:10000"/> </wsdl:port> </wsdl:service> </wsdl:definitions>

```
Hope it help

Thks
Balint

**Comment by fmontesi** [comment]
Thanks a lot, Balint!

I see some weird null.wsdl etc. used as namespaces around the WSDL generated by jolie2wsdl. That's weird, probably some parameters missing and jolie2wsdl does not tell the user?

**Comment by bmaschio** [comment]
@fmontesi 
Hi Fabrizio
Definitely not error signal by jolie2Wsdl see  screenshot under 

![image](https://cloud.githubusercontent.com/assets/12083716/7367980/0d695368-eda4-11e4-80d3-e396872bc270.png)

probably because i have not defined --tns parameter like in the second run

![image](https://cloud.githubusercontent.com/assets/12083716/7368044/9e24cee6-eda4-11e4-9cc3-b1794de4c6f4.png)

Now the problem is different is given by the Java Class generation that finds identical names for entities in the WSDL document
![image](https://cloud.githubusercontent.com/assets/12083716/7368123/4ce5bbfc-eda5-11e4-8aac-441f7e1156b8.png)

I think we need to  work on the Jolie2Wsdl Command Parser to either give some standard values or raise an exception  
Plus i think we could maybe add a warning that  inform the user to use different names for each entity of the WSDL

**Comment by klag** [comment]
Yes I think we definitevely need to improve jolie2wsdl and wsdl2jolie tools in order to be more usable by developers

**Comment by fmontesi** [comment]
@klag Git says that you introduced these parameters that are causing the nulls, so you probably had a practical motivation for them (probably you needed to match some namespaces needed by a third-party?). Could you check out #37 and give a very brief explanation of what each parameter does? Then, I think the tool should be patched to quit with an error when they are not specified since they are apparently very important, or at least they should have a sane default for each clearly stated in jolie2wsdl --help

**Comment by bmaschio** [comment]
@fmontesi @klag  Yesterday I had a bit of a thought about the process of biding  between java and WSDL structures I found this very usefull link

https://netbeans.org/kb/74/websvc/jaxb.html

now in the binding process we can define a configuration on naming of Java Classes this should in theory solve the problem with the importing wsdl with conflictal name
I had a go with a a file of configuration 

```xml
<jxb:bindings version="1.0" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<jxb:bindings schemaLocation="./TestWsdl.xsd" node="/xs:schema">
  <jxb:globalBindings bindingStyle="modelGroupBinding">
    <jxb:schemaBindings>
      <jxb:package name="example"/>
    </jxb:schemaBindings>
        </jxb:globalBindings>
  </jxb:bindings>
</jxb:bindings>
```
I have generated the TestWSDL.xsd from the Jolie generated WSDL and tryed to regenerate the classes yet i get a some problems with the importing of Binding definition
But I think this could be a way to solve the problems of Java/WSDL binding my reasoning is based on this two concepts 

1) the generated wsdl simce to work of SoapUi so lets not fix something that works
2) the fact that Java gives the possibility of defining a binding configuration it gives me the idea that the native process of binding is not so straight forward

What do you think about this?

**Comment by bmaschio** [comment]
@fmontesi @klag 

Right a little step have been done with the following jxb file

```xml
<jaxws:bindings
    wsdlLocation="../wsdl/TestWsdl.wsdl"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:jaxws="http://java.sun.com/xml/ns/jaxws"
    xmlns:jaxb="http://java.sun.com/xml/ns/jaxb">
    
    <jaxb:bindings node="wsdl:definitions/wsdl:types/xs:schema/xs:complexType[@name='GetCitiesByCountry']">
      <jaxb:class name="GetCitiesByCountry_Complex_Type"/>
    </jaxb:bindings>
    <jaxb:bindings node="wsdl:definitions/wsdl:types/xs:schema/xs:complexType[@name='GetCitiesByCountryResponse']">
      <jaxb:class name="GetCitiesByCountryResponse_Complex_Type"/>
    </jaxb:bindings>
</jaxws:bindings>
```
I have managed to solve the name conflict due to the identical name used in both element definition 

![image](https://cloud.githubusercontent.com/assets/12083716/7484230/8820d102-f386-11e4-8681-9189665145f4.png)

Used in the 

![image](https://cloud.githubusercontent.com/assets/12083716/7484263/c24d1c8c-f386-11e4-9639-b17534a3707b.png)

Now I am not sure why it is so  but again I am not a WSDL expert 

I will move on defining better the marshal and unmarshal properties in jxb 

Tnks

Balint

**Comment by mwallnoefer** [comment]
So if this is dependent on #44, we could close this?
