### ISSUE TITLE
Importing multiple copies of the same service

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#39]
Something I don't like about our current implementation of the standard library is that it is difficult to use multiple copies of the same service.

For example, if one wants to use one instance of Database, we simply need to do:

    include "database.iol"
    
    main { ... query@Database(x)(y) ... }

This works very nicely for one database (include and go!), but what if I need to connect to two different databases? I cannot include database.iol twice, since that will define all interfaces and outputport in database.iol twice, causing an error. A user is thus forced to actually delve into our code in database.iol and find out that another copy can be created like this:

    include "database.iol"

    outputPort Database2 { Interfaces: DatabaseInterface }

    embedded { Java: "joliex.db.DatabaseService" in Database2 }
    
    main { ... query@Database(x)(y) ... query@Database2(r)(s) ... }

What bugs me in particular is that we need to know the string "joliex.db.DatabaseService", which I may want to change in the future, and that I need two constructs (outputPort and embedded), but maybe it's just me. Is it bugging somebody else or do you find our current way of doing things fine?

**Comment by thesave** [comment]
From the top of my head and thinking with backward compatibility in mind, we could add, along with out-of-the-box (OTB) includes (the ones we already have, e.g., database.iol), their interfaces (e.g., database_interface.iol, which would be used by the OTB includes) and embeddable services (e.g., database_embeddable.iol also using the *_interface.iol).

If we want to have several instances of the same service we can do something like this

```
include "database_interface.iol"
outputPort DB1{ Interfaces: DatabaseInterface }
outputPort DB2 { Interfaces: DatabaseInterface }
embedded { Jolie: "database_embedding.iol" in DB1, "database_embedding.iol" in DB2 }
```

which would also come handy if we want to load new instances of a service at runtime (e.g., a registry of databases)

```
include "runtime.iol"
include "database_interface.iol"
outputPort DB{ Interfaces: DatabaseInterface }

main
{
  db[0].type = "Jolie";
  db[0].filepath = "database_embedding.iol";
  loadEmbeddedService@Runtime( db[0] )( db[0].location );
  ...
  DB.location = db[0].location;
  ...
}
```

It is indeed wordier than the "normal" include but is seems a good trade-off wrt the expressivity of the command.

**Comment by fmontesi** [comment]
Yes, we could surely go somewhere by splitting include files (maybe create a subdirectory for each service where we have the include files). Maybe not exactly like that though, because your solution implies that I must use Jolie services whereas I would like to be able to embed Java services. Also, I would like to abstract from the type of services they are (if it is Jolie or Java or Javascript I should not care). This last bit seems nontrivial with the current Jolie but maybe I'm missing something.

**Comment by bmaschio** [comment]
@fmontesi @thesave 

This very interesting , and I have been thinking about it for long time. In my mind ( that thing that keeps me grounded ) this is not a real language issue but  more a architectural issue. Normally I would go about in this way

1) A single service for each  DB
2) An service that acts as an orchestrator that adds the business logic

So let's say I have to extract data from both DB
```xml
[orchestratorOp1()(
 op1@DbService1()(reponseDb1);
 opN@DbService2()(reponseDb2);
/* Some king of data mapping*/
response = mapped data
)]{nullProcess}
```
Your solution all though very pretty they kind change , in my opinion , the king of micro services paradigm implemented by jolie

tnks

**Comment by fmontesi** [comment]
@bmaschio I agree with you, we should have a Jolie service for each database. Note though that this is kinda what also @thesave suggested: in his solution, we would have exactly one service per db.

Perhaps what I am really annoyed by is that bootstrapping a new Jolie program is too long. I would like some kind of macro the get the basics done immediately (a main procedure with an input port and an interface).

@thesave Do you think that we could have this kind of macros in SublimeJolie? I would really love to have a series of templates for some kinds of services (e.g., a database frontend, a rest service, a proxy, etc.) to kickstart developing a new Jolie service for a given purpose.

**Comment by bmaschio** [comment]
@fmontesi  @thesave what about creating macro on the false line of maven archetype we could create a small webserver where ppl could download an architype for a Jolie server and run a JolieArchetype tool to generate all  boring part

**Comment by fmontesi** [comment]
That sounds very cool for projects (importing an entire project structure) but not so cool for editing because it would require me having an internet connection, am I wrong?

**Comment by bmaschio** [comment]
@fmontesi I suppose what i was saying we will have a Jolie Archetype repository then a tool that download locally a copy of the archetype definition then when ever you want you create a new project using a specific archetype

In my mind would be

jolieArch --pull   name_archetype  (retrieve archetype) Internet Connection needed
jolieArch --push -name_archetype  (push archetype) Internet Connection needed
jolieArch -create  name_archetype directory_deploy

What do you think

**Comment by fmontesi** [comment]
Right, that would be cool. Maybe we can integrate it as an extra command in JPM?

I think that the best way to handle archetypes is using git. We could create a git repo for Jolie archetypes and then the tool would clone these repos locally. Maybe it's time to create a Jolie service to use git from Jolie a bit more natively... ;-)

**Comment by thesave** [comment]
Regarding SublimeJolie, it should be fairly easy to have static snippets for frequently-used patterns -- e.g., the `println` snippet came up to quicken my debugging sessions :)

The repository of archetypes would be the perfect place to take snippets from.

**Comment by bmaschio** [comment]
@fmontesi i suppose we could use the java GitHub API I could start looking into it what you think i would structure it this way

GitService ==> general pourpose  GIT integratione
JolieArchService ==> Uses GitService 

The advantage is that we could save ourself the pain of  handle login versioning ecc ecc ecc

**Comment by bmaschio** [comment]
@fmontesi Now there are several "Java Api " but fundamentally they all go through some  json calls  
Now shell we pick up Java API or make our from scratch?

**Comment by fmontesi** [comment]
Can you post here a link (or links) to these APIs to have a quick look?

**Comment by bmaschio** [comment]
https://developer.github.com/libraries/

In particular 

http://github-api.kohsuke.org/

I have downlodad the last one and doing the a simple example

**Comment by fmontesi** [comment]
That's the API for github, not git. Does it support cloning repos?

- F

**Comment by bmaschio** [comment]
@fmontesi 
It seems to be able to handle branching not sure cloning

**Comment by bmaschio** [comment]
@fmontesi 
I have tested the Java API

Starting from the login and repository list

```xml
	    Map<String, GHRepository> mapRepository = GitHub.connectUsingPassword("bmaschio77@gmail.com", "my Pass").getUser("bmaschio").getRepositories();
	    Iterator<String> iterator = mapRepository.keySet().iterator();
	    GHRepository reporsitory = null;
	    while (iterator.hasNext()){
	       String repositoryName = iterator.next();
	       reporsitory = mapRepository.get(repositoryName);
	    }
```
This seems to be able to get able to get all the 

```xml
	    Map<String, GHBranch> branches = reporsitory.getBranches();
	    Iterator<String> iteratorBranches = branches.keySet().iterator();
	    GHBranch branch = null;
	    while (iteratorBranches.hasNext()){
		 String nameBranches = iteratorBranches.next();
		 System.out.println(nameBranches);
		 branch = branches.get(nameBranches);
	    }
```
And then i save some data locally
```xml
	    List<GHContent> listContent = reporsitory.getDirectoryContent("tools/jolie2java");
	    Iterator<GHContent> contentIterator = listContent.iterator();
	    while (contentIterator.hasNext()){
		GHContent content = contentIterator.next();
		System.out.println (content.getHtmlUrl());
		if (content.isFile()){
		    System.out.println("isFile");
		    InputStream inputStream = content.read(); 
		    File file = new File("download/"+content.getName());
		    FileOutputStream out = new FileOutputStream(file);
		    int sizeFile = (int) content.getSize();
		    byte[] bytes = new byte [sizeFile];
		    out.write(bytes);
		    out.close();
		    
		}
	    }
```

So I would say that is working fine 

I think we should start thinking on an interface for gitHub

Thanks
-B

**Comment by fmontesi** [comment]
OK. I think that the best is probably doing it as in package control: we
download tagged releases.

How about using this?

https://developer.github.com/v3/git/

I think that from each section we can get an interface, and then we will
put all these interfaces in an output port GitHub or something like that.

Let's start slow, with a single interface and one or two operations.

- Fabrizio

**Comment by bmaschio** [comment]
@fmontesi 

I had a look to the API and they are rather powerfull

I have created a  access_token and tried several of the exposed API
```xml
/*to get the repo info
https://api.github.com/user/repos?access_token=xxxxxxxxxxxx

with is json answer

[
  {
    "id": 34453344,
    "name": "jolie",
    "full_name": "bmaschio/jolie",
    "owner": {
      "login": "bmaschio",
      "id": 12083716,
      "avatar_url": "https://avatars.githubusercontent.com/u/12083716?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bmaschio",
      "html_url": "https://github.com/bmaschio",
      "followers_url": "https://api.github.com/users/bmaschio/followers",
      "following_url": "https://api.github.com/users/bmaschio/following{/other_user}",
      "gists_url": "https://api.github.com/users/bmaschio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bmaschio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bmaschio/subscriptions",
      "organizations_url": "https://api.github.com/users/bmaschio/orgs",
      "repos_url": "https://api.github.com/users/bmaschio/repos",
      "events_url": "https://api.github.com/users/bmaschio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bmaschio/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/bmaschio/jolie",
    "description": "The Jolie Language Interpreter",
    "fork": true,
    "url": "https://api.github.com/repos/bmaschio/jolie",
    "forks_url": "https://api.github.com/repos/bmaschio/jolie/forks",
    "keys_url": "https://api.github.com/repos/bmaschio/jolie/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/bmaschio/jolie/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/bmaschio/jolie/teams",
    "hooks_url": "https://api.github.com/repos/bmaschio/jolie/hooks",
    "issue_events_url": "https://api.github.com/repos/bmaschio/jolie/issues/events{/number}",
    "events_url": "https://api.github.com/repos/bmaschio/jolie/events",
    "assignees_url": "https://api.github.com/repos/bmaschio/jolie/assignees{/user}",
    "branches_url": "https://api.github.com/repos/bmaschio/jolie/branches{/branch}",
    "tags_url": "https://api.github.com/repos/bmaschio/jolie/tags",
    "blobs_url": "https://api.github.com/repos/bmaschio/jolie/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/bmaschio/jolie/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/bmaschio/jolie/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/bmaschio/jolie/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/bmaschio/jolie/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/bmaschio/jolie/languages",
    "stargazers_url": "https://api.github.com/repos/bmaschio/jolie/stargazers",
    "contributors_url": "https://api.github.com/repos/bmaschio/jolie/contributors",
    "subscribers_url": "https://api.github.com/repos/bmaschio/jolie/subscribers",
    "subscription_url": "https://api.github.com/repos/bmaschio/jolie/subscription",
    "commits_url": "https://api.github.com/repos/bmaschio/jolie/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/bmaschio/jolie/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/bmaschio/jolie/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/bmaschio/jolie/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/bmaschio/jolie/contents/{+path}",
    "compare_url": "https://api.github.com/repos/bmaschio/jolie/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/bmaschio/jolie/merges",
    "archive_url": "https://api.github.com/repos/bmaschio/jolie/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/bmaschio/jolie/downloads",
    "issues_url": "https://api.github.com/repos/bmaschio/jolie/issues{/number}",
    "pulls_url": "https://api.github.com/repos/bmaschio/jolie/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/bmaschio/jolie/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/bmaschio/jolie/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/bmaschio/jolie/labels{/name}",
    "releases_url": "https://api.github.com/repos/bmaschio/jolie/releases{/id}",
    "created_at": "2015-04-23T11:55:09Z",
    "updated_at": "2015-04-28T15:20:49Z",
    "pushed_at": "2015-04-28T19:25:48Z",
    "git_url": "git://github.com/bmaschio/jolie.git",
    "ssh_url": "git@github.com:bmaschio/jolie.git",
    "clone_url": "https://github.com/bmaschio/jolie.git",
    "svn_url": "https://github.com/bmaschio/jolie",
    "homepage": "http://www.jolie-lang.org/",
    "size": 65140,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": false,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "permissions": {
      "admin": true,
      "push": true,
      "pull": true
    }
  }
]

/*gets all the branches for my user and the jolie repository
https://api.github.com/repos/bmaschio/jolie/branches?access_token=xxxxxxxxxxxx

here is the json answer
[
  {
    "name": "BalitBranch",
    "commit": {
      "sha": "510893ad22569b8f1773eed92e3eee4bc07be395",
      "url": "https://api.github.com/repos/bmaschio/jolie/commits/510893ad22569b8f1773eed92e3eee4bc07be395"
    }
  },
  {
    "name": "gwt-removal",
    "commit": {
      "sha": "216fca2e45ba9854b7f65354a95837102aacb0f6",
      "url": "https://api.github.com/repos/bmaschio/jolie/commits/216fca2e45ba9854b7f65354a95837102aacb0f6"
    }
  },
  {
    "name": "master",
    "commit": {
      "sha": "b9424410db35b7701e05cdd6974ddc3e08a106bc",
      "url": "https://api.github.com/repos/bmaschio/jolie/commits/b9424410db35b7701e05cdd6974ddc3e08a106bc"
    }
  }
]
```
My idea was to define a series of Jolie interfaces and and define a series of output port
I had a go with this idea but not luck i had a series of problem 
1) we can not use api.github.com in the location but its ip address socket://192.30.252.139:443/repos/bmaschio/jolie/
2) I am not sure how to ( my fault ) how to use https in a output port 
3) Once i have menage to set up a kind of dummy test i get an error 

this is the code for the example
```xml
interface GitHubReposCollaborators {
    RequestResponse:
    collaborators(undefined)(undefined)

}
outputPort GitHub{
  Location: "socket://192.30.252.139:443/repos/bmaschio/jolie/"
  Protocol: https {
  	.debug = true;
  	.compression = false;
  	.method
  }
  Interfaces: GitHubReposCollaborators
}


main{
   request.access_token="d115b33b3a10eb58d21b991aba0af3046fa8aaae";
   collaborators@GitHub(request)(response)

}
```
```xml
mag 03, 2015 4:57:22 PM jolie.Interpreter logInfo
INFORMAZIONI: [main_git_hub.ol] java.io.IOException: Remote party closed SSL con
nection
        at jolie.net.ssl.SSLProtocol.wrap(SSLProtocol.java:156)
        at jolie.net.ssl.SSLProtocol.handshake(SSLProtocol.java:276)
        at jolie.net.ssl.SSLProtocol.handshakeIfNeeded(SSLProtocol.java:325)
        at jolie.net.ssl.SSLProtocol.read(SSLProtocol.java:308)
        at jolie.net.ssl.SSLProtocol.access$000(SSLProtocol.java:56)
        at jolie.net.ssl.SSLProtocol$SSLInputStream.read(SSLProtocol.java:78)
        at java.io.InputStream.read(Unknown Source)
        at jolie.net.http.HttpParser.readAll(HttpParser.java:252)
        at jolie.net.http.HttpParser.readContent(HttpParser.java:334)
        at jolie.net.http.HttpParser.parse(HttpParser.java:360)
        at jolie.net.HttpProtocol.recv_internal(HttpProtocol.java:1223)
        at jolie.net.http.HttpUtils.recv(HttpUtils.java:129)
        at jolie.net.HttpProtocol.recv(HttpProtocol.java:1342)
        at jolie.net.ssl.SSLProtocol.recv(SSLProtocol.java:431)
        at jolie.net.SocketCommChannel.recvImpl(SocketCommChannel.java:95)
        at jolie.net.CommChannel.recv(CommChannel.java:198)
        at jolie.net.AbstractCommChannel$ResponseReceiver.run(AbstractCommChanne
l.java:227)

```

@fmontesi
Do you think we need to implemet it using Java

tnks
-B

**Comment by fmontesi** [comment]
On Mon, May 4, 2015 at 9:48 AM, Balint Maschio <notifications@github.com>
wrote:

> My idea was to define a series of Jolie interfaces and and define a series
> of output port
>
> I had a go with this idea but not luck i had a series of problem
> 1) we can not use api.github.com in the location but its ip address
> socket://192.30.252.139:443/repos/bmaschio/jolie/
> 2) I am not sure how to ( my fault ) how to use https in a output port
> 3) Once i have menage to set up a kind of dummy test i get an error
>
>
> You can use domain names in Jolie, but you still have to use the port,
e.g.,

Location: "socket://api.github.com:443/repos/bmaschio/"

Can you try making an example that does not require authentication first,
so that we can discuss that one? I don't know if you're using it properly,
you're just passing it in the querystring and I don't think that's how it's
supposed to work.

As soon as do that, @mwallnoefer and I can test if https is working
properly for this.

**Comment by bmaschio** [comment]
@fmontesi Nope I can not it seems that all the github API require autentication.

I have tryed with

"socket://api.github.com:443/repos/bmaschio/"
you can use the token in the example for your test 

tnks
Balint

**Comment by fmontesi** [comment]
OK. What kind of request do we have to form, in HTTP? I'm pretty sure we
have the parameters for it already, but we need to know what headers or
data we should send.

- Fabrizio

**Comment by bmaschio** [comment]
@fmontesi

https://api.github.com/repos/bmaschio/jolie/collaborators?access_token=d115b33b3a10eb58d21b991aba0af3046fa8aaae


https://developer.github.com/v3/repos/collaborators/

hope it is usefull

**Comment by fmontesi** [comment]
Very, thanks!

@mwallnoefer here's the example I'm trying to run then:

<pre>
interface GitHubReposCollaborators {
    RequestResponse:
    collaborators

}
outputPort GitHub{
Location: "socket://api.github.com:443/repos/bmaschio/jolie/"
Protocol: https {
        .debug = true;
        .compression = false;
        .method = "get"
}
Interfaces: GitHubReposCollaborators
}


main
{
   request.access_token="d115b33b3a10eb58d21b991aba0af3046fa8aaae";
   collaborators@GitHub(request)(response)
}
</pre>

Does it work for you? I'm getting:

<pre>
May 04, 2015 1:55:25 PM jolie.Interpreter logInfo
INFO: [github.ol] java.io.IOException: Remote party closed SSL connection
        at jolie.net.ssl.SSLProtocol.wrap(SSLProtocol.java:156)
        at jolie.net.ssl.SSLProtocol.handshake(SSLProtocol.java:276)
        at jolie.net.ssl.SSLProtocol.handshakeIfNeeded(SSLProtocol.java:325)
        at jolie.net.ssl.SSLProtocol.read(SSLProtocol.java:308)
        at jolie.net.ssl.SSLProtocol.access$000(SSLProtocol.java:56)
        at jolie.net.ssl.SSLProtocol$SSLInputStream.read(SSLProtocol.java:78)
        at java.io.InputStream.read(InputStream.java:170)
        at jolie.net.http.HttpParser.readAll(HttpParser.java:252)
        at jolie.net.http.HttpParser.readContent(HttpParser.java:334)
        at jolie.net.http.HttpParser.parse(HttpParser.java:360)
        at jolie.net.HttpProtocol.recv_internal(HttpProtocol.java:1227)
        at jolie.net.http.HttpUtils.recv(HttpUtils.java:129)
        at jolie.net.HttpProtocol.recv(HttpProtocol.java:1346)
        at jolie.net.ssl.SSLProtocol.recv(SSLProtocol.java:431)
        at jolie.net.SocketCommChannel.recvImpl(SocketCommChannel.java:95)
        at jolie.net.CommChannel.recv(CommChannel.java:198)
        at jolie.net.AbstractCommChannel$ResponseReceiver.run(AbstractCommChannel.java:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by mwallnoefer** [comment]
No, for me it quits with the same error.

**Comment by bmaschio** [comment]
@mwallnoefer @fmontesi Can I help to debug the issue?

**Comment by fmontesi** [comment]
I created an open issue: #41

Let's get to the bottom of this, it's unclear whether we had this problem
before or not. We seem to be working fine with Twitter in the Jolie website.

**Comment by fmontesi** [comment]
Et voila', fixed! :-)

See here for the client: https://gist.github.com/fmontesi/fff1897f615c13b31fcb

It works now, and github responds correctly!
