### ISSUE TITLE
Jolie Request Response does not respond if run from IDE

### ISSUE THREAD

**Issue by AlbertoGaragnani** [jolie/jolie#396]
**Describe the bug**
If I run a simple jolie service with a request-response operation from IDE, when I try to send an HTTP message to the service (inputPort) it doesn't respond with the expected response. 
It works completely fine if run form terminal.

**To Reproduce**
1. Use the following code or any other request-response code:
```
type GreetRequest { name:string }
type GreetResponse { greeting:string }

interface GreeterAPI {
    RequestResponse: greet( GreetRequest )( GreetResponse )
}

service Greeter {
    execution: concurrent // Handle clients concurrently

    inputPort GreeterInput {
        location: "socket://localhost:8080"
        protocol: http { format = "json" }
        interfaces: GreeterAPI
    }

    main {
        greet( request )( response ) {
            response.greeting = "Hello, " + request.name
        }
    }
}
```
2. Run it from IDE (https://github.com/jolie/jolie/wiki/IDEs-and-Debugging)
3. Send an Http message (curl http://localhost:8080/greet?name=Jolie)
4. Nothing happens.

**Expected behavior**
I should get the response message ({"greeting":"Hello, Jolie"}).

**Screenshots**
![Immagine_2022-05-17_112813](https://user-images.githubusercontent.com/101807848/168778774-94bf78b6-03b9-4ae5-89eb-ed953979c73b.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04 LTS]
 - Jolie version [1.10]
 - Java Version [JDK11]

**Additional context**
Running jolie services on IDE's gives problems even with OneWay opreations and in the debugging process.

@kicito
@fmontesi

**Comment by AlbertoGaragnani** [comment]
I am running the code i copied above from IDE with the following configurations:
Main Class: jolie.Jolie
Arguments: -l ./lib/:/lib/jolie/lib:/lib/jolie/javaServices/:/lib/jolie/extensions/* -i /lib/jolie/include -p /lib/jolie/packages service.ol
Working Directory: path/to/service.ol

I followed this link with some adjustment: https://github.com/jolie/jolie/wiki/IDEs-and-Debugging

**Comment by kicito** [comment]
I don't have any experience with Netbeans, I might not be able to help you much. The argument seems to be correct for me.

I am not sure if it is relatable but is the progress bar at the bottom of the IDE which stuck in 50% relevant in this case? And perhaps try debug the program with `--trace` argument before Jolie file like following

Arguments: -l ./lib/:/lib/jolie/lib:/lib/jolie/javaServices/:/lib/jolie/extensions/* -i /lib/jolie/include -p /lib/jolie/packages **--trace** service.ol

If the console prints out some text, that indicates the Jolie program is actually running in the process. From the code you provided it should produce following line then start listening to :8000

```
/path/to/file.ol:171.      :: DEEPCOPY     COPIED                  null                                            Value:
```

**Comment by AlbertoGaragnani** [comment]
I realised I was working on an old fork of the official repository and running the code from there. I synced it and now it works fine without changing arguments. 
Thanks a lot for your help
