### ISSUE TITLE
Improve the Sublime plugin and its visibility

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#40]
@thesave I use the Jolie plugin for Sublime Linter regularly now and I can't live without it. But, installing it is a bit quirky (has hardcoded directories) and the Jolie websites does it no justice (it's our mainly supported editor but that's not very visible).

@jolie/developers Have you tried it? Your life will change. I helped Saverio refactor it a bit to use libjolie and he was kind enough to do the coding, so now so you get online errors in the editor about what the jolie interpreter may not like (wrong operation names, wrong port names, missing interfaces, etc.). Since we use libjolie, this now means that improving the SemanticVerifier or OLParser in libjolie automatically also improved Sublime Jolie!

I mean, look at how nice it is:

![Sublime Jolie Linter](https://cdn.pbrd.co/images/70p4PcS.png)

We must fix this!

@thesave Can you tell us what we lack to make it easier to install for any generic Jolie installation?

After we fix this, the next item should probably be to make that underlining a bit more precise and to output more helpful messages from libjolie.

**Comment by thesave** [comment]
Happy the plugin is useful :)

> @thesave Can you tell us what we lack to make it easier to install for any generic Jolie installation?

@fmontesi could you be a little more specific on that? Probably an example would help me understand.

Meanwhile I added a [todo list](https://github.com/thesave/SublimeLinter-jolint#to-do) to the repository, this should make easy compiling a list of wanted features (pull requests).

**Comment by fmontesi** [comment]
On Thu, Apr 30, 2015 at 3:53 PM, thesave <notifications@github.com> wrote:

> Happy the plugin is useful :)
>
> @thesave <https://github.com/thesave> Can you tell us what we lack to
> make it easier to install for any generic Jolie installation?
>
> @fmontesi <https://github.com/fmontesi> could you be a little more
> specific on that? Probably an example would help me understand.
>
> Meanwhile I added a todo list
> <https://github.com/thesave/SublimeLinter-jolint#to-do> to the
> repository, this should make easy compiling a list of wanted features (pull
> requests).
>
Ah, implementing the second item would fix my problem I think. I had a
problem in installing it because I am not using the default installation
directory.

**Comment by bmaschio** [comment]
@jolie/developers 

Not sure this the right place but i have implemented some personal snippet, because i am quite  forgetful when it comes to including the standard service such console.iol so I have added some snippet that look like 

```xml
<snippet>
    <content><![CDATA[include "${0:console.iol}"]]></content>
    <tabTrigger>console</tabTrigger>
    <scope>source.ol</scope>
    <scope>source.iol</scope>
    <description>console standard library</description>
</snippet>
```

what do you think
b

**Comment by fmontesi** [comment]
For includes, I would like them to be triggered by "include" and then show
a list of all the possible include files that are reachable by the Jolie
program, but I may be dreaming... :-)

In general I think we need to write a microservice that gives all the
necessary API to support writing Jolie IDEs in a language-independent way.
Here we have the problem that Sublime uses Python. While we could use Py4J,
I think that the service-oriented way would be better.

**Comment by bmaschio** [comment]
@fmontesi that was my initial idea but I have not found a way to do it so in ne content fields. It seems not able to handle dynamic searches

**Comment by fmontesi** [comment]
Closed since @thesave added the dialog to the editor in his repo.
