### ISSUE TITLE
error message not understandable

### ISSUE THREAD

**Issue by klag** [jolie/jolie#400]
The following code contains a syntax error because a } is missing 
```
from OperationInterface import OperationInterface

service Div {
  inputPort Op {
    location:"local"
    interfaces: OperationInterface
  }

  main {
    run( request )( response ) {
        response = request.x / request.y
    
  }
}
```
The error on console is 
```
Index -1 out of bounds for length 0
```

The OperationInterface follows:
```
type RequestType {
  x: double
  y: double
}

/* this interface must be implemented by all the services which will be embedded by the parent one */
interface OperationInterface {
  RequestResponse:
    run( RequestType )( double )
}

```

**Comment by kicito** [comment]
@vickimixen Is this issue related to your recent PR? Otherwise, I could have a look :).

**Comment by vickimixen** [comment]
Yes, this is most probably my code. I will take a look at it :)

**Comment by fmontesi** [comment]
@vickimixen Could you post a screenshot of what you get? :)

**Comment by vickimixen** [comment]
@fmontesi Yes :)
![errorissue](https://user-images.githubusercontent.com/33627612/172317103-98b7e5bf-b6aa-4361-8f2d-717f72ff4696.png)

**Comment by fmontesi** [comment]
Looks good to me. Closing for now, but @klag please reopen in case you still encounter the same error with `master`.
