### ISSUE TITLE
1.10.8 release failure

### ISSUE THREAD

**Issue by chenrui333** [jolie/jolie#409]
Looks like [1.10.8 release was not successful](https://github.com/jolie/jolie/actions/runs/2588051595). Thanks!

**Comment by fmontesi** [comment]
Thanks!
It was because I forgot to update the version in `pom.xml`. Should be working now... let's see. :)

**Comment by fmontesi** [comment]
Fixed, but now the installer isn't working properly.. Moving the discussion to #413.
