### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#41]
We should look into cleaning up SSLProtocol.java, see the bug in #39.

@mwallnoefer I have commented out your HTTPS tests for now, as they seem to block test.ol. Are you up for helping in cleaning SSLProtocol? There's even dead code in there. :-) I'd be glad to help.

@bmaschio Maybe you are also interested in this?

**Comment by mwallnoefer** [comment]
@fmontesi The problem is that I have little knowledge in SSL. Also all these methods and this dead code...I have no idea what they mean etc. 

@bmaschio feel free to look into this if you want to :-).

**Comment by bmaschio** [comment]
@mwallnoefer  Ok I will have a go
@fmontesi  any good reference for ssl in java

**Comment by fmontesi** [comment]
Not much AFAIK

http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngine.html

And here's an example:

http://www.cs.lafayette.edu/docs/java/guide/security/jsse/samples/sslengine/SSLEngineSimpleDemo.java

The most important thing is probably to improve our error detection
mechanism. Currently, if something bad happens, we only get a "Connection
closed by remote peer" when trying to send something again. But *why* was
it closed? We need to know that to debug ssl.

**Comment by bmaschio** [comment]
@fmontesi Silly question should be time to work also with the monitor for protocol errors ?

**Comment by fmontesi** [comment]
What do you mean? Do you want to generate monitor events for protocol errors? That could be cool, but let's discuss it in a separate thread.

Or, are you talking about better output of errors on screen for SSL? (that's the first thing we need for this issue, if it's possible)

**Comment by bmaschio** [comment]
@fmontesi   Yes i was proposing that to raise a monitor event for all sort of protocol error 

I have looked to some of the documentation of the SSLResult result at it seems to to not have a lot of  info more then the status

**Comment by fmontesi** [comment]
@bmaschio Yeah error reporting in SSLResult seems really sub-optimal... Let's keep it simple for now and do monitoring later, I think we'll have enough problems fixing SSL as it is already.

**Comment by mwallnoefer** [comment]
Also this important issue deserves to be fixed. I remember that I have started the investigation but got stuck at some point.

@bmaschio was it you who volunteered for helping here? I don't recall anymore ...

**Comment by fmontesi** [comment]
@thesave has a student who's attempting a restructuring. @thesave can you keep us updated here?

**Comment by thesave** [comment]
Unfortunately, due to the time constraints of the delivery of the thesis, the student will not modify/refactor the class. However, the thesis should support the future restructuring of the class as it analyses (in italian) the general usage of SSLEngine, how it is integrated in SSLProtocol, and what updates are needed to give a better support to SSL in Jolie.

**Comment by fmontesi** [comment]
I've patched the branch java8 and now the bug seen in #39 has been fixed.

I have also taken the time to clean up some of the logic, the handling of buffers was unclear. I've found using the final keyword wherever possible useful to understand which parts of the state were mutable or not.

@mwallnoefer Your tests do not work yet but I think now we're near to fixing them. Can you have a look into that?

**Comment by mwallnoefer** [comment]
@fmontesi I had a quick look over your work which is great.

Could we first back-port the patches from 21.-27. August, since there seem to be real bug fixes? Then I would resume my investigation.

**Comment by fmontesi** [comment]
Thanks!

Yes, we can backport the changes to jolie-ssl. I didn't use anything that requires Java > 6. If you'd like to do it, I think that git cherry-pick should just work here (since I made very local changes).

**Comment by fmontesi** [comment]
By the way, I did *not* focus on efficiency with the buffer management, but rather on readability (I copy buffers around sometimes even when that could be avoided). Let's stick to simplicity for a while until we reach a point where everything works. :-)

**Comment by mwallnoefer** [comment]
@fmontesi I attempted the backport but the server.ol test is not passing yet: https://github.com/mwallnoefer/jolie

I guess that you also changed some internal buffering code to fix the SSL bug (PreBufferedInputStream?). I hope you can give me a clue.

**Comment by fmontesi** [comment]
As I mentioned, your tests do not work yet, even in the java8 branch, where all patches are in. So backporting also PreBufferedInputStream would not fix it I think.

**Comment by mwallnoefer** [comment]
Ah I thought they worked, since you dropped the comment signs :)

**Comment by mwallnoefer** [comment]
Finally fixed.

**Comment by fmontesi** [comment]
Woohoo! :+1:
