### ISSUE TITLE
HttpTemplate header value is never assigned 

### ISSUE THREAD

**Issue by kicito** [jolie/jolie#410]
**Describe the bug**
The `outHeader` never get assigned with a static value during HTTP send

**To Reproduce**
Execute following code with `--trace` flag

```
interface AIface {
    RequestResponse: getData(void)(void)
}

service main {

    outputPort A {
        location: "socket://example.com:443/"
        protocol: https { 
            osc.getData << {
                method = "POST"
                outHeaders.("Authorization") = "test"
                outHeaders.("Api-Version") = "2"
                outHeaders.("Api-Application") = "test"
                outHeaders.("Api-Company") = "test"
                outHeaders.("User-Agent") = "test"
            }
        }
        interfaces: AIface
    }
    main {
        getData@A(void)(response)
    }
}

```
result: 
```
[httpheader.ol]         4.      HTTP    HTTP MESSAGE SENT                       /[HTTP debug] Sending:
POST /getData HTTP/1.1
Host: example.com
Accept-Encoding: gzip, deflate
Authorization: 
Api-Version: 
Api-Company: 
User-Agent: 
Api-Application: 
X-Jolie-MessageID: 1
X-Jolie-ServicePath: /
Content-Type: text/xml; charset=utf-8
Content-Length: 10
```
**Expected behavior**
The header is sent with the assigned value i.e. Authorization: test

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Jolie version master@219de8ef28e1fa3707454ea2c0b47bcf880f0111
 - Java Version openjdk version "11.0.15" 2022-04-19

**Additional context**
I am not aware if it is by design or not but it seems like the value will get set only if the header value is bonded to the request value 
https://github.com/jolie/jolie/blob/53d307285f700363f090102082218c2e0d857825/extensions/http/src/main/java/jolie/net/HttpProtocol.java#L894

**Comment by fmontesi** [comment]
Mmh I think that these are designed exactly for fetching subnodes from messages and make them header values. @bmaschio right?

@kicito Do you need to define the header values statically for some reason?

**Comment by kicito** [comment]
If it was designed this way I am fine with it. I was confused when seeing the string value define a field name instead of an arbitrary string in this case. But I can also see the benefit of having the ability to define a header value at the port level such as, in this case, the Authorization token is pre-generated and was meant to use for every request between the server and the application.
