### ISSUE TITLE
SOAP message charset bug

### ISSUE THREAD

**Issue by klag** [jolie/jolie#42]
take the following service and transform it in a web service using jolie2wsdl.

If you send a SOAP message with a request message that contains more than two special characters like "à", the service will reply with a truncated message.

Service
_________
include "console.iol"

execution{ concurrent }

type TestType: void {
	.message: string
}

type TestTypeR: void {
	.message: string
}

interface MyInterface {
	RequestResponse:
		test( TestType )( TestTypeR )
}

inputPort MyPort {
	Location: "socket://localhost:9000"
	Protocol: soap {
		.wsdl = "test.wsdl";
		.wsdl.port = "MyPortServicePort"
	}
	Interfaces: MyInterface
}

main {	
	test( request )( response ) {
		response.message = request.message
	}
}

Request message example that raises the bug
_______________________________________

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:prov="prova.xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <prov:test>
         <message>etssààà</message>
      </prov:test>
   </soapenv:Body>
</soapenv:Envelope>

Generated wsdl
_______________________________________

<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="prova.wsdl" xmlns:tns="prova.wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd1="prova.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xs:schema targetNamespace="prova.xsd" xmlns:sch="prova.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema"><xs:element name="test"><xs:complexType><xs:sequence><xs:element maxOccurs="1" minOccurs="1" name="message" type="xs:string"/></xs:sequence></xs:complexType></xs:element><xs:element name="testResponse"><xs:complexType><xs:sequence><xs:element maxOccurs="1" minOccurs="1" name="message" type="xs:string"/></xs:sequence></xs:complexType></xs:element></xs:schema>
  </wsdl:types>
  <wsdl:message name="TestTypeR">
    <wsdl:part name="body" element="xsd1:testResponse"/>
  </wsdl:message>
  <wsdl:message name="TestType">
    <wsdl:part name="body" element="xsd1:test"/>
  </wsdl:message>
  <wsdl:portType name="MyPort">
    <wsdl:operation name="test">
      <wsdl:input message="tns:TestType"/>
      <wsdl:output message="tns:TestTypeR"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MyPortSOAPBinding" type="tns:MyPort">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http/"/>
    <wsdl:operation name="test">
      <soap:operation soapAction="test" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MyPortService">
    <wsdl:port name="MyPortServicePort" binding="tns:MyPortSOAPBinding">
      <soap:address location="http://localhost:9000"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>

**Comment by klag** [comment]
sorry the wsdl has been partially uploaded. You can generate it using jolie2wsdl

**Comment by fmontesi** [comment]
You can use <pre> tags to make that stuff look correctly. But I think we're covered in any case. :-)

@mwallnoefer  could it be solved by one of your charset patches maybe? I guess it's a charset problem.

**Comment by mwallnoefer** [comment]
@fmontesi If the special char is written in a string literal in the source file, just specify the correct source file's charset using the --charset parameter.

**Comment by bmaschio** [comment]
@klag @fmontesi @mwallnoefer 
hi guys i think i solved it the problem was given by the absence of the CHARACTER_SET_ENCODING property in the SoapMessage 

@mwallnoefer  
Is it the same correction you have done ?

I have committed the change on my branch

Here is the test

![image](https://cloud.githubusercontent.com/assets/12083716/7492552/5c860c6a-f3f9-11e4-8241-442597d30bb1.png)


Thanks

**Comment by mwallnoefer** [comment]
Ok, I have pushed the fix (34339b91c04e84b49bb07d5a9295e5a8e7faa0e6).
Interesting that the character set encoding needs to be specified twice, since it was already contained in the XML header.
