### ISSUE TITLE
Invalid encoding name ""UTF-8""

### ISSUE THREAD

**Issue by klag** [jolie/jolie#43]
If we create a jolie interface starting from the wsdl of the service described at #42 and we try to use the following client for invoking that web service, we will get the error:

Invalid encoding name ""UTF-8""

Client
________
include "console.iol"
include "myWsdlInterface.iol"

main {
	request.message = "ciao";
	test@MyPortServicePort( request )( response );
	println@Console( response.message )()
}

where myWsdlInterface.iol is the interface generated with the wsdl2jolie tool starting from the wsdl of #42

**Comment by mwallnoefer** [comment]
@klag @bmaschio Does the problem persist after applying the CHARACTER_SET_ENCODING change?

**Comment by mwallnoefer** [comment]
My tests showed that it has been fixed.
