### ISSUE TITLE
++ and -- do not work with long

### ISSUE THREAD

**Issue by klag** [jolie/jolie#432]
`    a = 1662929984215L
    a++
    println@Console( a )()    `
    
    the result is `777640662`

if we try
`    a = 1662929984215L
    a = a + 1
    println@Console( a )()  `

the result is `1662929984216`

**Comment by fmontesi** [comment]
@kicito Could you add a test and look into this?

**Comment by kicito** [comment]
I am just playing with it a bit. It seems like the error is during typecasting while sending the message

```
from console import Console

service main{
    embed Console as Console

    main{
        // issue 432
        a = 1662929984215L
        a++

        if ( a != 1662929984216L ) {
        	throw( TestFailed, "expected 1662929984216, received " + a )
        }
        println@Console( a )()
    }
}
```
$ jolie --trace 432.ol 
432.ol  1.      ^ LOAD  Java Service Loader                     ConsoleService
/home/nau/sdu/jolie-playground/432.ol:92.       :: ASSIGNMENT   ASSIGN                  null                                            Value::long = 1662929984215

/home/nau/jolie-playground/432.ol:143.      << SR   println@Console                 SENDING MSG_ID:1
                                                Value::int = 777640664

/home/nau/jolie-playground/432.ol:144.      << SR   println@Console                 SENT    MSG_ID:1
                                                Value::int = 777640664

777640664
/home/nau/jolie-playground/432.ol:145.      << SR   println@Console                 RECEIVED        MSG_ID:1
                                                Value:
```

I will keep looking for the cause of this bug.

**Comment by fmontesi** [comment]
@kicito your test indicates the post-increment primitive is doing something wrong, maybe a cast.
Browsing the source of PostIncrementProcess confirms this..

```
val.setValue( val.intValue() + 1 );
```

We should check what the type of val is in that code.

This makes me think that the same problem probably holds for --x, ++x, x--, ...
