### ISSUE TITLE
Possible bug in redirection

### ISSUE THREAD

**Issue by thesave** [jolie/jolie#435]
Hi all,

I stumbled upon a possible bug with redirection — I was playing with dynamic redirection, but I could reproduce it statically and I assembled this MWE. 

If I run the code below

```jolie
service s {

 inputPort in {
  location: "socket://localhost:8001"
  protocol: http
  requestResponse: echo
 }

 execution: concurrent

 main { echo(t)(t) }

}

service main {

 embed s

 outputPort so {
  location: "socket://localhost:8001"
  protocol: http
  requestResponse: echo
 }

 inputPort in {
  location: "socket://localhost:8000"
  protocol: http
  redirects:
   s => so
 }

 main { linkIn( a ) }

}
```
with the command `jolie -s main main.ol` (main.ol is the file containing the code) and then run 
`curl localhost:8000/\!/s/echo`, the call becomes stuck and the console running the Jolie service outputs the warning

```
#main.ol#s#0
WARNING: [#main.ol#s#0] Discarded a message for resource echo, not specified in the appropriate redirection table.
#main.ol#s#0
SEVERE: Discarded a message for resource echo, not specified in the appropriate redirection table
```

The same happens when I make the call from Chrome (minus the escape `\` in `\!` in the URL). 
If I call the service with a Jolie client everything works well.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Jolie version: 1.10.13
 - Java Version:  17.0.1

**Bonus Bug**

If I set the protocol of service `s` to `sodep` (so, both in the inputPort of `s` and the outputPort of `main`) I get

    Exception in thread "Thread-1" java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "str" is null
    at jolie.net.SodepProtocol.writeString(SodepProtocol.java:77)
    at jolie.net.SodepProtocol.writeMessage(SodepProtocol.java:167)
    at jolie.net.SodepProtocol.send(SodepProtocol.java:261)
    at jolie.net.SocketCommChannel.sendImpl(SocketCommChannel.java:118)```

Maybe a bug linked to having undefined-typed operations and the translation between http and sodep?
Also in this case, calling from a Jolie client works as expected.

**Comment by fmontesi** [comment]
Hi Saverio,
You have to terminate the redirection path with another !/, so you get:
```
curl localhost:8000/\!/s\!/echo
```

The "bug" in sodep is probably because the resource is not there or something, would be nice to have a better error message by performing a check.
