### ISSUE TITLE
Using import * detects duplicate declaration of symbols

### ISSUE THREAD

**Issue by EmilOvcina** [jolie/jolie#457]
**Describe the bug**
Using the `import *` notation detects duplicate declarations if the file being imported has an import which also exists in the file using `import *`

**To Reproduce**
1. Create an interface and two services all in separate files
2. Create an `inputPort` in one of the services with `local` location using the interface created before. Import the interface
3. Create an `outputPort` in the other service using the same interface and import the interface.
4. In the service with the `outputPort`, embed the first service `in` the output port
5. Import the embedded service using the star notation: `from .s1 import *`

**Expected behavior**
The imports in the imported files should not populate the namespace of the file importing *

**Screenshots**
![](https://i.imgur.com/QYMfbzv.png)

**Desktop (please complete the following information):**
 - OS: mac os
 - Jolie version 1.11.0-git
 - Java Version 11

**Comment by fmontesi** [comment]
Thanks for the clear report!

@kicito we're likely not filtering out the imported symbols of a module when importing from it.

**Comment by fmontesi** [comment]
@kicito  is this fixed now?

**Comment by kicito** [comment]
Yes, it should be. If the problem still persists, please reopen the issue. Thanks!
