### ISSUE TITLE
HTTP - no response content on one-way operations

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#467]
I suggest to _not_ send back a default payload (in JSON `{}`) with an apposite content-length header on one-way operations or when the response type has been set to `void`.
Although this may be perfectly ok with standard HTTP "200 OK" responses, others like "204 No Content" (often seen on DELETE operations) should not provide it since it causes undefined semantics.

**Comment by fmontesi** [comment]
I'm generally ok with this.
For one-ways, never sending `{}` back sounds good.
For RRs, I wonder. `{}` has type `void` after all. What does the standard say?

**Comment by mwallnoefer** [comment]
Hi Fabrizio, regarding the status code _204_ (https://datatracker.ietf.org/doc/html/rfc9110#section-15.3.5-5)
> A 204 response is terminated by the end of the header section; it cannot contain content or trailers.

So we somehow need to provide a way to _not_ send back any payload with an apposite `Content-Length` header. Hence I guess it is sound to use the _one-way_ operations on the http protocol which at the moment are handled like _r-r_ ones with a return value of `void`.

As far as I know we had _always_ suggested to use _r-r_ operations when it comes to the http protocol, so I am not concerned about changing the semantics of the _one-way_ ones.

**Comment by mwallnoefer** [comment]
PR #469

**Comment by mwallnoefer** [comment]
And then we are still not done. According to this code sample: https://docs.jolie-lang.org/v1.11.x/language-tools-and-standard-library/rest/index.html#programming-a-self-contained-rest-service.

Suppose adding a one-way operation _deleteUser_:
```
OneWay:
    deleteUser( ViewUserRequest )
```

Then in _main_ I am not allowed to write a request handler within an input choice like this:
```
        [ deleteUser ( request ) {
       // change the HTTP status code to 204
        } ]
```

I could do it after the brackets, but then the response has already been sent before the alteration of the status code takes effect:
```
        [ deleteUser ( request ) ] {
       // change the HTTP status code to 204
        }
```
