### ISSUE TITLE
Error when trying to import parameters using an external file

### ISSUE THREAD

**Issue by klag** [jolie/jolie#468]
It seems that a lib is missing, because when I am trying to pass parameters by means of a json file I see this error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException
	at jolie.Jolie.main(Jolie.java:80)
Caused by: java.lang.ClassNotFoundException: org.json.simple.parser.ParseException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 1 more
```

the command is:

```
jolie --params parameters.json main.ol
```

**Comment by kicito** [comment]
Hi, could you please provide the resources to reproduce the error?

**Comment by klag** [comment]
The service is:

```
include "message_digest.iol"
include "console.iol"

type ParamType {
  test:string
}

service MyService ( p : ParamType ) {
  main {
      println@Console( p.test )()
  } 
}
```

the json file is:
```
{
    "test":"hello"
}
```

the comnand line is:
```
jolie --params param.json test.ol

```

the output is:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException
	at jolie.Jolie.main(Jolie.java:80)
Caused by: java.lang.ClassNotFoundException: org.json.simple.parser.ParseException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 1 more

```

**Comment by kicito** [comment]
Could you retest with master or v1.11.2? When I run the provided code, it works as expected ( printing 'hello' ).

**Comment by fmontesi** [comment]
How did it happen that your launcher was not updated?

**Comment by klag** [comment]
It is because when I update my repo locally and I compile, usually I only update the jolie libs, not the launchers.

Anyway, in production envirnoment, usually I do not have a launcher for any version, but I have a launcher and then I just change the JOLIE_HOME for pointing the version of jolie.

This is not a goof solution I know, but the installation process we have so far does not help

**Comment by klag** [comment]
@fmontesi @kicito

**Comment by fmontesi** [comment]
> It is because when I update my repo locally and I compile, usually I only update the jolie libs, not the launchers.
> 
> Anyway, in production envirnoment, usually I do not have a launcher for any version, but I have a launcher and then I just change the JOLIE_HOME for pointing the version of jolie.
> 
> This is not a good solution I know, but the installation process we have so far does not help

I see your issue, but detecting whether the launcher is the right one is not gonna help much: you will still have to keep separate launchers for each version of Jolie.

**Comment by klag** [comment]
I solved that problem, but I added another problem. See above my last comment

**Comment by fmontesi** [comment]
Yeah, I was playing with it, and I could reproduce it. @kicito, any ideas?

**Comment by kicito** [comment]
The error is due to the behavior of Jolie's JSON parser. To accept a JSON array from the parameter the type must read from `_` field. So the code will look like this

```jolie
from console import Console
type ParamType {
  test:string
  array {
    _*: string 
  }
}

service MyService ( p : ParamType ) {

  embed Console as Console
  main {
      println@Console( p.test )()
      for( i in p.array._ ) {
        println@Console( i )()
      }
  } 
}
```

**Comment by klag** [comment]
but it is possible to correctly convert a json object into a jolie array when there is a type declaration, we alredy do this when we receive and send messages in a http port.

I think that the solution is to import the parameters together with the type declaration, and the problem will be solved

**Comment by mwallnoefer** [comment]
This matches issue #264, let's continue the discussion there.
