### ISSUE TITLE
ParserException with comments (//) at the end of Jolie source files

### ISSUE THREAD

**Issue by thesave** [jolie/jolie#47]
I get a parse exception for the code below

    include "console.iol"
    main { println@Console( "hello world" )() } 
    // this is a comment

It seems it regards comments at the end of Jolie source files.
I report below the error stack.

       jolie.InterpreterException: jolie.lang.parse.ParserException: /Users/thesave/Desktop/test.ol:3: error: Invalid token encountered. Found token type ERROR
		at jolie.Interpreter.buildOOIT(Interpreter.java:1270)
		at jolie.Interpreter.init(Interpreter.java:1037)
		at jolie.Interpreter.run(Interpreter.java:1112)
		at jolie.Jolie.main(Jolie.java:59)
	Caused by: jolie.lang.parse.ParserException: /Users/thesave/Desktop/test.ol:3: error: Invalid token encountered. Found token type ERROR
		at jolie.lang.parse.AbstractParser.throwException(AbstractParser.java:197)
		at jolie.lang.parse.OLParser._parse(OLParser.java:221)
		at jolie.lang.parse.OLParser.parse(OLParser.java:183)
		at jolie.Interpreter.buildOOIT(Interpreter.java:1218)
		... 3 more

Do you experience the same behaviour?

**Comment by fmontesi** [comment]
Nope, I don't, neither on Linux nor MacOS.

**Comment by thesave** [comment]
What version of java are you using?

I tried it on both Mavericks and Yosemite with java 1.7.0_79 and got that error.
FYI, I just tried the program on a Ubuntu machine (trusty, java 1.7.0_80), no error whatsoever.

**Comment by fmontesi** [comment]
1.8.0-40ea

Let me know if that makes a difference... interesting. Also, have you tried
inserting a newline at the end of the file? It doesn't make a difference
for me but maybe you have a weird character somewhere?

**Comment by thesave** [comment]
I re-wrote the test to avoid copy-pasting "strange" characters.
The error is still there but if I add a new line after the comment it works fine.

Maybe it is something linked to the encoding and end-of-line characters.

FIY `/* comment */` raises no error.

As soon as I have some time I will look into this.

**Comment by fmontesi** [comment]
@thesave Any news on this?

**Comment by thesave** [comment]
I am looking into this right now.

**Comment by thesave** [comment]
My last push should have fixed the issue.

On a side-note, I run the test suite under Windows and the Converter service returns an "strings invalid length/size" error. Later I will open an issue on that.

**Comment by fmontesi** [comment]
Close an issue, open an issue.. :-)

**Comment by mwallnoefer** [comment]
You have to run the testsuite with --charset utf-8, since Windows per default uses latin1.
