### ISSUE TITLE
HTTP - make it possible to set the status code as a constant

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#470]
At the moment it is not possible to set the `statusCode` parameter in the HTTP protocol as a constant. 

In other words,
```
inputPort HTTPInput {
  protocol: http {
     statusCode -> statusCode...
```
is possible, but the following snippet does not work:
```
inputPort HTTPInput {
  protocol: http {
    statusCode = statusCode // OR EVEN statusCode = "200"...
```

And yields to the WARNING that an invalid `statusCode = 0` was passed. How could we do better and support both?

**Comment by fmontesi** [comment]
Do you get the same error if you try `statusCode = 200`?

**Comment by mwallnoefer** [comment]
No, unfortunately not and this is a showstopper for one-way calls as I have written in issue https://github.com/jolie/jolie/issues/467#issuecomment-2004486744.

```
WARNUNG: [main.ol] HTTP protocol for operation ... is sending a message with status code 0, which is not in the HTTP specifications.
```

**Comment by mwallnoefer** [comment]
I guess we may close this now that we support custom success status codes over the `osc` arguments: https://docs.jolie-lang.org/v1.11.x/language-tools-and-standard-library/rest/index.html
