### ISSUE TITLE
Giving the possibility to selct memory sizes in the launcher

### ISSUE THREAD

**Issue by klag** [jolie/jolie#472]
It would be nice to have the possibility to specify some extra JVM parameters like -Xms and Xmx because it could be important to limit the memory usage of a component.

I see two possibilities:
1- we abstract away from the underlying JVM and we select those parameters we think are suitable for a Jolie engine, then we implement them for the current Java implementatio  of Jolie (preferable, but it requires more effort)
2- we just give the possibility to add JVM parameters in the Jolie launcher

Maybe at the present we could proceed with 2, but in the long term 1 is preferable

**Comment by fmontesi** [comment]
I've found out that you can just pass params to the JVM through the JAVA_TOOL_OPTIONS env var, for example `JAVA_TOOL_OPTIONS="-Xmx50m" jolie main.ol`. I guess that's good enough for now.
