### ISSUE TITLE
HttpScanner.java - Fix code scanning alert - Useless comparison test

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#481]
Tracking issue for:
- [x] https://github.com/jolie/jolie/security/code-scanning/1788

Hi Fabrizio,

this is a valid hit, since currently the parser contains two branches for parsing a division char (/). Moreover in the state 12 the further parsing sequence is commented out. Maybe delete this alltogether?

**Comment by fmontesi** [comment]
Yeah, I agree. HttpScanner is derived from Scanner in libjolie, and probably fixes were not ported. I wonder if we need all these cases in HttpScanner actually.

**Comment by mwallnoefer** [comment]
PR #497
