### ISSUE TITLE
When doing a response on client request can't add custom headers

### ISSUE THREAD

**Issue by lunatik-210** [jolie/jolie#49]
Initially I tried to enable CORS so that there were a need for me to response with additional headers on client request.

I tried this way as it's said in documentation.

inputPort Server {
    Location: "socket://localhost:5000/"
    Protocol: http {
        .method = "get";
        .addHeader.header[0] <<"X" {.value="Y"};
        .statusCode -> statusCode
    }
    Interfaces: SumInterface
}

So, I looked through the sourcecode on gihub and found out that the implementation of send_appendResponseHeaders don't include custom headers for response that makes impossible to make CORS request from browser. 

see here https://github.com/jolie/jolie/blob/e6ba8d1bace0e70803a3f02f094e69a3613fd986/extensions/http/src/jolie/net/HttpProtocol.java#L590 

However, there is one line of code for request: https://github.com/jolie/jolie/blob/e6ba8d1bace0e70803a3f02f094e69a3613fd986/extensions/http/src/jolie/net/HttpProtocol.java#L737

So, probably it's a BUG to fix.

**Comment by fmontesi** [comment]
@jolie/developers 

I think it's time we streamline the handling of headers, we have too many options and we lack this important one that @lunatik-210 was expecting.

We need to be able to distinguish between request and response headers, and assign them both globally to the port or per single operation. Sometimes headers should be fetched from the Jolie value we're sending. Anybody who would like to get involved in this?

**Comment by bmaschio** [comment]
@fmontesi I would like to do this

**Comment by fmontesi** [comment]
Thanks Balint! I propose that we come up with the syntax for the parameters first.

A first idea could be to have two sub-structures that we use to distinguish when one parameter should be used for requests or responses:

    Protocol: http {
        .request.method -> method;
        .response.headers.("Content-Type") = "application/json"
    }

This would have the beautiful property that they would work for both output and input ports, i.e., if .request.method is "GET", then if it in an input port it means that we received a message with method GET, otherwise if it is in an output port it means that we have to send a message with method GET. In turn, this would enable us to transparently send protocol configurations around to clients that need to use them.

Any other ideas? @jolie/developers please try to follow this, it'll have a big impact. We should try to make the current parameters continue to work, by interpreting them in their new form but outputting a "DEPRECATED" message.

**Comment by bmaschio** [comment]
@fmontesi @jolie/developers  I quite like it 
I have a silly idea that goes like this

```javascrip
Protocol: http {
    .request.method -> operationName.request.fieldName;
    .request.unHandleHeader -> default.FieldName
    .response.operarationName.headers.("Content-Type") = "application/json"
}

```javascript

The first will allow specify a "push" of request header to a specific operation   request type fieldname
The second is to create a general "container" variable  unHandleHeader for all those header parameters non contemplated in the current implementation   
The third  creasy idea will be to specify at operation level the heather constants 
What do you think

Balint

**Comment by fmontesi** [comment]
Mmh, I don't think it would work like that, the operation name should be part of the parameter name to be able to distinguish them. For example we could reuse the `osc` data structure:

     .osc.operationName.request.method = "get"

**Comment by fmontesi** [comment]
OK, I thought a while about it and I'm kinda convinced. To sum it up:

     .request.method -> var

The usual, the HTTPProtocol implementation writes into .request.method and this just happens to be a link to var, so var gets written.

     .osc.operationName.request.method -> var

As above, but only for operationName. This takes *precedence* over .request.method (if we have a configuration for an operation, it's more specific and therefore has priority over the generic parameter).

We do the same for .response.

I would start only with two parameters for now: method (for request only, as responses do not have a method in HTTP) and headers (for both request and response).

For putting stuff inside of messages (read from headers) and "unhandled headers", I would wait. It looks like we can solve it architecturally by introducing a router service (I'm doing it for REST and it works well, I'll post something about it as soon as it's presentable). Let's start small with .request and .response.

What do you think?

**Comment by mwallnoefer** [comment]
@fmontesi I am okay with your proposal.

**Comment by bmaschio** [comment]
@fmontesi it is ok for me @klag is it ok for you ? If I remember well you use intensively the HTTP protocol

**Comment by fmontesi** [comment]
PS: we should retrofit the old parameters to use these new ones, and
possibly print a "Deprecated" message with Interpreter.logWarning()

**Comment by fmontesi** [comment]
@klag Any comments? Otherwise, @bmaschio please go ahead with a minimal working parameter when you can and let's discuss it.

**Comment by bmaschio** [comment]
@fmontesi   @mwallnoefer @lunatik-210 
First of all  sorry for the long delay been very busy with other 1000 things anyhow this the beta version of the implementation I have defined the both a operation specific  response header and a global one that should works for both op1 and op2 ( sorry fantasy is not my strongest point )  
```javascript
inputPort HTTPInput {
Protocol: http {
	.keepAlive = 0; // Do not keep connections open
	.debug = 1; 
	.debug.showContent = 1;
	.format -> format;
	.contentType -> mime;
	.cookies.cookie1 = "cookie1";
	.response.headerData1 -> headerData1;    
	.osc.op2.cookies.cookie2 = "cookie2";
    .osc.op1.response.headerData -> headerData;
    .compression = false;
	.default = "default"
}
```
where the implementation looks like
```javascript
	[ op1( request )( response ) {	
                headerData = "tryDataOp1";
                headerData1 = "tryData1Op1";
		valueToPrettyString@StringUtils (request)(s);
                println@Console("op1>>>>"+s)();
                response = "op1 Request = " + s
	} ] { nullProcess }

	[op2 (request)(response){
                headerData1 = "tryData1Op2";
	  	valueToPrettyString@StringUtils (request)(s);
                println@Console("op2>>>>"+s)();
                response = "op2 Request = " + s
	}]{nullProcess}
```
The following picture shows the response for op1
![image](https://cloud.githubusercontent.com/assets/12083716/9065727/c9f68984-3ad3-11e5-8a89-7c153bf22195.png)


and then for op2

![image](https://cloud.githubusercontent.com/assets/12083716/9065707/a062c0d8-3ad3-11e5-9d45-dd1fe31a4000.png)

What do you think about it?

**Comment by fmontesi** [comment]
Looks like a good start!

I think that the `request` and `response` parameters will be useful also for other things (e.g., getting the format of the request and set the format of the response separately).

So instead of

    .response.headerData1

I would use a substructure `headers` like this:

    .response.headers.headerData1

How about that?

**Comment by bmaschio** [comment]
@fmontesi 

Ok i will do it  after 24th going to holiday for two weeks

**Comment by bmaschio** [comment]
@fmontesi 
Sorry for the delay but I was super busy back from 2 week of holiday, now it looks like this

```javascript

inputPort HTTPInput {
Protocol: http {
	.keepAlive = 0; // Do not keep connections open
	.debug = 1; 
	.debug.showContent = 1;
	.format -> format;
	.contentType -> mime;
	.cookies.cookie1 = "cookie1";
	.response.headers.headerData1 -> headerData1;    
	.osc.op2.cookies.cookie2 = "cookie2";
        .osc.op1.response.headers.headerData -> headerData;
         . compression = false;
	.default = "default"
}

```

![image](https://cloud.githubusercontent.com/assets/12083716/9737585/a26d5fca-5647-11e5-89f8-26d153158b2c.png)

what do you think??

Balint

**Comment by fmontesi** [comment]
Hi Balint, thanks a lot for your work! I'm swamped right now, will have a
look at this asap.

**Comment by fmontesi** [comment]
Sorry for the long wait, I think that it looks really good now. :+1: 

@bmaschio can you propose a pull request for the java8 branch?

I would start with only .response.headers for now, OK?

@mwallnoefer @klag can you help with the reviewing?

**Comment by mwallnoefer** [comment]
Has this been merged already?

**Comment by bmaschio** [comment]
@mwallnoefer soory for the delay been very busy. Once again not sure how to commit the code. do I need to work always on my personal copy or can i commit on the main copy in the repository

**Comment by bmaschio** [comment]
@mwallnoefer I have committed it  3bcd169

**Comment by fmontesi** [comment]
Hi all,

Please use pull requests so that we can all look at the code. @mwallnoefer
can you have a look?

- Fabrizio

**Comment by bmaschio** [comment]
@fmontesi 
Ho can i keep my branch continuously aligned with the main one?

**Comment by mwallnoefer** [comment]
I do not find this commit id. You need to push it at least to your remote "master" branch (bmaschio/jolie).
Only then I can integrate it.

**Comment by fmontesi** [comment]
For keeping aligned, I think that you need to pull from jolie/master (I
don't have the means to get the necessary pointers for the exact command
line right now..).

**Comment by bmaschio** [comment]
I get this.....
![image](https://cloud.githubusercontent.com/assets/12083716/11217906/f118776c-8d52-11e5-983f-99104b9011af.png)

**Comment by fmontesi** [comment]
Hi Balint,

Very weird, diff says the *whole* file changed, so I can't review it. :-(

@mwallnoefer can you help checking what's going on?

Meanwhile, can you guys revert the commit please?

- Fabrizio

**Comment by mwallnoefer** [comment]
@bmaschio you need to configure your editor better (line ending)

btw. you can inspect the diff by:
> git show --ignore-space-at-eol

**Comment by fmontesi** [comment]
Thanks, @mwallnoefer ! And thanks to @bmaschio for the patch. Wonderful! :-)
