### ISSUE TITLE
SOAP root values

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#5]
Currently, SOAP does not transmit root values of messages.

This is however, only a WSDL 1.1 limitation, and prevents programs using, e.g., SODEP or HTTP to be ported to SOAP.

I think that we should transmit root values and leave this limitation only to when WSDL is used.
Please comment if you think that SOAP has this as an inherent protocol limitation or not.

**Comment by klag** [comment]
I agree, better if we put a parameter for setting this

**Comment by mwallnoefer** [comment]
Well, maybe I still not get the real issue. I have tried the WSDL SOAP example on http://docs.jolie-lang.org/#!documentation/web_services/web_services.html with enabling the root value. I did not get any type casting problem, so when exactly it causes harm?

> diff --git a/extensions/soap/src/jolie/net/SoapProtocol.java b/extensions/soap/s
> index 6187718..d7c0d7a 100644
> --- a/extensions/soap/src/jolie/net/SoapProtocol.java
> +++ b/extensions/soap/src/jolie/net/SoapProtocol.java
> @@ -998,7 +998,7 @@ public class SoapProtocol extends SequentialCommProtocol {
>                 if (soapFault == null) {
>                     Element soapValueElement = getFirstElement(soapMessage.getS
>                     messageId = soapValueElement.getLocalName();
> -                    xmlNodeToValue(value, soapValueElement, true);
> +                    xmlNodeToValue(value, soapValueElement, false);
>
>                     ValueVector schemaPaths = getParameterVector("schema");
>                     if (schemaPaths.size() > 0) {

**Comment by fmontesi** [comment]
All those types have void as root type, so I guess they are not influenced since there is no value to encode anyway?

**Comment by mwallnoefer** [comment]
Well we have also another instance of xmlNodeToValue(...true) a few lines later, when we create an error message:
                } else {
                    String faultName = "UnknownFault";
                    Value faultValue = Value.create();
                    Detail d = soapFault.getDetail();
                    if (d != null) {
                        Node n = d.getFirstChild();
                        if (n != null) {
                            faultName = n.getLocalName();
                            xmlNodeToValue(
                                    faultValue, n, true);
                        } else {
                            faultValue.setValue(soapFault.getFaultString());
                        }
                    }
                    fault = new FaultException(faultName, faultValue);
                }
Here it might be correct to drop the root, which exists and in the interface could have been defined void. Thoughts?

But in the former case we could safely change true -> false without breaking anything, right?

**Comment by fmontesi** [comment]
My two cents:
- I think that silently dropping values, roots or not, is not a good practice. The developer will see this as unexpected and will enter debugging nightmare. So, if and when we drop a root, it should be an explicit parameter. Actually, I think we should never drop the root and simply give a TypeMismatch error somewhere but please let me know what you think if you had experience with this (especially @klag ).
- When we import an interface from WSDL, it won't have roots with type different from void. So we won't have problems there.
- When we export a Jolie interface containing roots that are not void to WSDL, the jolie2wsdl tool should just throw an exception and notify the user that the interface cannot be exported.

That said, what is the concrete use case in which dropping a root saves us? I'd like to know a bit more about it.

**Comment by mwallnoefer** [comment]
I fully agree. Probably we even do not need a parameter here.

**Comment by mwallnoefer** [comment]
@klag could you please comment here? I would prefer to push my patch with changing true -> false since we see no real issue.

**Comment by fmontesi** [comment]
Here's maybe a better suggestion than my last one:

- in jolie2wsdl, we map all root nodes to a subnode called "root" in the WSDL document;
- by default, SOAP works as normal without doing anything weird to roots;
- when the .wsdl parameter is supplied to SOAP, we apply the same trick and all roots go to a "root" subelement.

@klag Would that work for the scenarios that motivated the behaviour we have now?

**Comment by klag** [comment]
jolie2wsdl: if you put the root in a subfield called "root" then the SOAP message will have a subfield called root. So the soap protocol, will put all the subfield called "root" as root values of the tree? I really do not like this.

If I remember well I introduced the dropping of a TEXT_NODE in the root because I dealt with a very bad soap client that sent to my jolie web service a soap message with CRLF at the end of each tag line.
Thus, an empty string was placed as root value of the message.

Web services are usually a nightmare.

Since a SOAP message should not contain root values, I think we could simply drop them in order to avoid messages with a bad format. Moreover, as I said in the ML, I think we should release a bets practice for providing a web service with Jolie, that is: do not use root value in the message types.

**Comment by mwallnoefer** [comment]
Yeah, I agree with you that using "simple" return values is not the best solution.
But for fixing the issue we could fall-back to the parameter solution. My question is: did you have only one single bad experience, so I would set the drop to a default "false".

**Comment by fmontesi** [comment]
Ok i agree with all of you, as long as the drop is disabled by default so
that we do not surprise developers unaware of this (regardless of how well
documented this will be, it's just weird and breaks our usual "it just
works" methodology for protocols).

I still think jolie2wsdl should throw a warning at least.

**Comment by mwallnoefer** [comment]
Okay I push the patch.
