### ISSUE TITLE
Refinement: regex limitations 

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#512]
While improving the OpenAPI-2-Jolie conversion tools I have stumbled across the following limitation in the types `regex` clause:

source: https://docs.jolie-lang.org/v1.11.x/language-tools-and-standard-library/basics/data-types/index.html#refinement-regex
```
type MyType {
    email: string( regex(".*@.*\\..*") )
}
```
Such clauses seem to implicitly embed the RE within the line boundaries `^` and `$`, while Swagger REs (`pattern` clauses) are not required to do so. The converters need to be fixed in order to eliminate these characters in _openapi2jolie_ and re-introduce them in _jolie2openapi_.

But when we meet REs with choices it becomes more complicated: `"pattern": "^IT[0-9]{6}$|^DE[0-9]{8}$"`. Just to be sure to not remove the caret (`^`) accidentally since it could also introduce a negation: `[^`.

Minor issue: In Jolie REs, `\d` respectively `\\d` was never recognised in my tests, so I had to convert them to `[0-9]`.

**Comment by mwallnoefer** [comment]
PR #513

**Comment by fmontesi** [comment]
It's probably a limitation of the regex library that we use:

https://www.brics.dk/automaton/doc/dk/brics/automaton/RegExp.html

The reason for choosing that one is that we wanna keep interface compatibility checking decidable for future use, so having the possibility to check for language inclusion is important. We might wanna add our own preprocessing perhaps? Just some simple expansions, for example.

**Comment by mwallnoefer** [comment]
I have tried to ask them for adding the support for the standard character classes but it seems not to be part of their wish-list: https://github.com/cs-au-dk/dk.brics.automaton/issues/46.
