### ISSUE TITLE
Invalid constant definition via "-C" parameter under Windows

### ISSUE THREAD

**Issue by thesave** [jolie/jolie#53]
Setting constants via the relative option <code>jolie -C c=42 program.ol</code> returns the error:

<code>Invalid constant definition, reason: expected = after constant identifier Server_location, found token type EOF</code>

I think it should not be a difficult fix but unfortunately I do not have the time to fix it. Can someone look into this?

**Comment by mwallnoefer** [comment]
I cannot reproduce this under GNU/Linux, but have not yet tried with Windows.

**Comment by fmontesi** [comment]
@thesave @mwallnoefer Any news about this?

@thesave : do you still have the error on master? If so, could you send a test to try it out?

**Comment by mwallnoefer** [comment]
I am sorry for not answering so long. The issue is valid indeed and I get the same error on Windows XP, interesting.

**Comment by thesave** [comment]
It seems Java under Windows strips away the "=" (equal) sign.
If you run any Jolie program under Windows with the command 
	
	jolie -C c=42 program.ol

it returns the error 

	Invalid constant definition, reason: expected = after constant identifier c, found token type EOF

because what it is actually passed to the interpreter in the `args' array is

	["-C", "c", "42" , "program.ol" ]

If you issue the same command enclosing the assignment in quotes 

	jolie -C "c=42" program.ol

everything works as expected.

**Comment by fmontesi** [comment]
Wow, just.. wow.

Can you test if this is a problem that appears with embedding too, please?

embedded {
Jolie: "-C c=42 program.ol"
}

If embedding is not affected, we can just document this behaviour on the website.. would be great to find a resource on the Internet explaining precisely what Windows (probably cmd.exe?) is doing.

**Comment by thesave** [comment]
Works flawlessly.

I dug a little, AFAIU it is because in Windows "=" [is a parameter separator](http://ss64.com/nt/syntax-esc.html#delimiters) just like commas.

**Comment by fmontesi** [comment]
OK, phew. Shall we just make a note about this on the website then? Maybe
also on the --help string?

**Comment by thesave** [comment]
Ok, I updated the --help string and the docs.

**Comment by fmontesi** [comment]
Awesome, thanks! :-)

**Comment by mwallnoefer** [comment]
Ah, I just wanted to report the same as @thesave did ;).

http://stackoverflow.com/questions/30760965/run-bat-command-line-jvm-argument-not-passed-as-expected/30761153#30761153
