### ISSUE TITLE
Use of cookies in HTTP

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#54]
@jolie/developers 
I am getting a bit stuck in the use of the cookies
Let me try to show you what I am trying to use

```javascript
inputPort HTTPInput {
Protocol: http {
	.keepAlive = 0; // Do not keep connections open
	.debug = DebugHttp; 
	.debug.showContent = DebugHttpContent;
	.format -> format;
	.contentType -> mime;
    .cookies.sid  = "aaaaaaa";
	.default = "default"
}
Location: Location_Leonardo
Interfaces: HTTPInterface, ExampleInterface
}
```
I was expecting to set a cookies named "sid" and with value "aaaaaa"

**Comment by bmaschio** [comment]
@jolie/developers 

I Think I have solved by myself. Yet I think some extra example on jolie sites would be usefull 

```javascript
inputPort HTTPInput {
Protocol: http {
	.keepAlive = 0; // Do not keep connections open
	.debug = DebugHttp; 
	.debug.showContent = DebugHttpContent;
	.format -> format;
	.contentType -> mime;
    .cookies-> cookies;
	.default = "default"
}
Location: Location_Leonardo
Interfaces: HTTPInterface, ExampleInterface
}

//somewhere in the code of an operation we get

cookies = "sid=prova"; 

```javascript

**Comment by fmontesi** [comment]
Hi Balint,

Here's an example:

    .cookies.sidCookie = "sid"

means that there will be a cookie called "sidCookie" in the HTTP messages, and that its content will be mapped to the subnode "sid" inside of Jolie messages, for example

    myOp( x )( y ) { println@Console( x.sid )() }

Thanks for going ahead and trying to improve the docs in the website issue! Let's continue the discussion there.
