### ISSUE TITLE
Use the Files class in FileService

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#55]
FileService (file.iol) implements operations that are now provided by the Files class since Java 7.

Whoever wants to take a shot at replacing our custom implementations with the standard ones from Files, feel welcome to give it a try. Please remember to use the java8 branch, since master is still targeted at Java 6.

**Comment by mwallnoefer** [comment]
I think that we started to do so, hence we could close this one?

**Comment by fmontesi** [comment]
Correct. Done :)
