### ISSUE TITLE
ant test task for Windows

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#56]
@thesave @mwallnoefer 

I have recently added a test task to ant (so that we can run "ant test" on the command line) that runs the test suite. This was necessary to integrate our build system with [Travis-CI](https://travis-ci.org/) (you can see the build status on our readme file now).

I have added a dummy target -test-windows for implementing the functionality on Windows (I've already put the check for the OS). Could you try to implement it by copying and modifying appropriately the target -test-unix ? The main differences are hopefully that we need to run cmd instead of sh and that we need to add the parameter suggested by @mwallnoefer at the end of issue #47 .

That way, we can stop running tests manually (`jolie test.ol`) and instead use `ant test` which does the right thing (tm) in the OS we are using at the moment.

What do you think?

**Comment by thesave** [comment]
My last commit should do it, someone with Windows can confirm it works properly?

**Comment by mwallnoefer** [comment]
ATM I am on holidays, but I will test it after coming back. The patches look correct to me.

**Comment by mwallnoefer** [comment]
Works perfectly here with Windows XP.
