### ISSUE TITLE
HTTP - implement content negotiation

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#66]
According to HTTP RFC 7231 we should accept content negotiation over the **Accept** and the **Accept-Charset** headers ("Accept-Encoding" is already supported by us, "Accept-Language" needs to be handled at user's side).
These seem very useful features to me. At the moment I would prefer to just implement the simple (unweighted syntax).

https://tools.ietf.org/html/rfc7231#section-5.3

**Comment by fmontesi** [comment]
Sounds good to me! :-)

Please make sure that the java8 branch is also updated with this if you decide to work on master. Otherwise, you can just work on java8 and backport. Although java8 is broken right now since some libs are broken due to the introduction of type choices.

**Comment by fmontesi** [comment]
Was this merged or am I remembering incorrectly?

**Comment by mwallnoefer** [comment]
For now it was just a proposal.

**Comment by mwallnoefer** [comment]
PR #478
