### ISSUE TITLE
Apache HData

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#73]
@jolie/developers 
HI All
In the enterprise side of things one of the buzz words is big data and vertical DBase, so i thought how can we use jolie to work with big data, are micro-services suited for this task. So I started wandering if there was an open version of vertical DBase. And I found HData of Apache. I was wandering if anyone wants to help me with a possible implementation of a Jolie service
Regards
Balint

**Comment by fmontesi** [comment]
Hi Balint,
Can you provide a link? HData is used in different contexts.

As for Big Data, we're trying to get a framework set up at the University of Southern Denmark with Jolie and Enorm (http://enorm.sdu.dk/), I don't know if that would suit your needs? It's similar to Apache Hadoop (for which it could also be interesting to develop some integration). @mawolf is the one who experimented with Enorm integration.

Cheers,
Fabrizio

**Comment by bmaschio** [comment]
Hi Fabrizio
I suppose there are very similar HData is db for Hadoop, I suppose it would be better passing though Hadoop and not directly on DB
https://hbase.apache.org/

**Comment by fmontesi** [comment]
Ah, HBase! That'd be very cool. The main difference between HBase and Enorm, as far as I know, is that Enorm is optimised towards the analysis and processing of streaming data, e.g., for doing statistics on clickstreams or service monitoring.

HBase is a really nice project, would be great to see some integration with it. They have a thrift gateway and a REST interface, so we may use those. I think that many people would probably also like integration with tools such as Redis.. still waiting for somebody to come up for that. :-)

**Comment by bmaschio** [comment]
Dohhhh I am so dumm on all this project names, I will have a look and continue the conversation

**Comment by fmontesi** [comment]
Hi @bmaschio , are you still looking into this or should I close it for now?

**Comment by bmaschio** [comment]
I was going to work after Mongo but  yes for the moment we can close it
