### ISSUE TITLE
Autocomplete Suggestions

### ISSUE THREAD

**Issue by mawolf** [jolie/jolie#75]
Hej all, :-)

A great annoyance for me is that I have to look up the definitions of ports and their interfaces when I develop in Jolie. I was therefore looking at implementing autocompletion in Atom and saw that clang provides an autocomplete interface which makes it possible to use it in various editors [1]. I find this highly beneficial and was looking at the Jolie parser to see whether it would be easy to implement this as well. However, before making changes to the important parser I would like to brainstorm a bit with some of the considerations that I have.
1. Overhead: Is it a good idea to put it in the parser? I assume it would get some overhead, and understand that this overhead could be okay with clang, but what about a language like Jolie?
2. Implementation: I see that the scanner already is keeping track about what line it is at and was thinking to have a simple if statement checking if it has reached the location for where the user would like to have suggestions, if this is the case, it should throw an exception that would make the parser catch it and come with suggestions.
3. Output format: What type of output format would be best? I see that clang actually have support for output in JSON.

Any ideas are highly welcome!

Best wishes,
Martin

[1] https://github.com/benogle/autocomplete-clang/blob/master/lib/clang-provider.coffee

**Comment by fmontesi** [comment]
Hi Martin,

Thanks for finding it out! There's a student working on the IDE but on
another task, still I think it would be useful to coordinate on the
backend. I'm away until Tuesday, I'll look into this then.

Cheers,
Fabrizio

**Comment by mawolf** [comment]
How did this end up? Is someone working or going to work on it?

**Comment by fmontesi** [comment]
@agwe Is anybody from IU working on this currently?

**Comment by mwallnoefer** [comment]
Okay, in the meantime we have autocompletion support in Visual Studio Code: https://jolie.github.io/news/2019/07/11/vscode-jolie.html
