### ISSUE TITLE
Google Cloud and Jolie

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#76]
@jolie/developers 

I think we should start looking a bit at this 

https://cloud.google.com/sql/

It seems to possess both a JSON interface and a Java API Library.

In my mind, would be cool to have a native service to work on SQL engine on cloud.

@fmontesi 
Did say somewhere that you were developing sono json/jolie tool or did I immagine it

**Comment by fmontesi** [comment]
I suspect it may work already, just by extending with the right parameter
(driver) the JDBC-based Database service. It says that they support
standard APIs, so maybe JDBC is one of them? I couldn't find any link to
the concrete API, could you share it if you found one?

About JSON, yes, Javascript services now are integrated with native JSON
support. I should write a blog post about that... :-)

**Comment by bmaschio** [comment]
Fantastic that is what I suspected, maybe then we could run some test with some example to put in a post o several post. The idea would be to show that Jolie is able without further libraries to connect to the DB in cloud. What you think?

**Comment by fmontesi** [comment]
Sounds great!

**Comment by bmaschio** [comment]
@fmontesi 
I the json tool already in the stable version of jolie...?

**Comment by fmontesi** [comment]
It's used for the new embedding mechanism of Javascript code, yes. But what do you need exactly? Maybe we need to factor it out and wrap around another API for you, depending on what you want to use it for.

**Comment by bmaschio** [comment]
@fmontesi 
this are the HTTP rest call 

https://cloud.google.com/sql/docs/admin-api/v1beta4/

the the libraries

https://cloud.google.com/sql/docs/admin-api/libraries

My thinking is either to take the java library and create a Jolie native service or using their libraries in JavaScript with the emberding

What you think

**Comment by fmontesi** [comment]
Why don't we just call the HTTP rest API directly?

**Comment by bmaschio** [comment]
Yes I agree we should try it and maybe create a tutorial on the jolie site..?

**Comment by fmontesi** [comment]
Is this still alive? Maybe it should be moved into a project of its own?

**Comment by bmaschio** [comment]
Yes let's move it to a project or its own
