### ISSUE TITLE
Missing root data selector when using Jolie tree structures

### ISSUE THREAD

**Issue by Ezbob** [jolie/jolie#79]
I have a problem when using tree data structures in Jolie;
How does one access the root node data and only the root node data in trees?

An example would be:
```
include "console.iol"
include "exec.iol"

main
{
	exec@Exec("pwd")(currentDir);
	moreFun = currentDir + "addFun";
	println@Console( moreFun )()
}
```  
The `currentDir` here refers to a tree containing at the root the current working directory as a string, and a child containing the program exit code from calling `pwd`. I would like to extend the string located at the root with another string, but running this example just prints out `"addFun"`.  

Maybe this problem could be solved using a special assessor for getting only the root data, seen as all other data can be assessed independently ?

**Comment by mwallnoefer** [comment]
Have you tried using a cast, e.g. moreFun = string(currentDir) + "addFun";

**Comment by Ezbob** [comment]
I have now, but I still get the same result.

**Comment by thesave** [comment]
Under OSX I get the current directory followed by a "\n" character. The final result is

```
my/Current/Directory
addFun
```

Does removing the trailing new line do what you mean?

```
include "console.iol"
include "string_utils.iol"
include "exec.iol"

main
{
    exec@Exec("pwd")(currentDir);
    pwd = currentDir;
    length@StringUtils( pwd )( pwdLength );
    pwd.begin = 0;
    pwd.end = pwdLength-1;
    substring@StringUtils( pwd )( currentDir );
    moreFun = currentDir + "addFun";
    println@Console( moreFun )()
}
```

**Comment by fmontesi** [comment]
As a side remark, that code is not portable (but you probably know), and
apparently we do not have a portable way in the File service. Would be nice
to have a workingDirectory operation (or whatever they call it in Java) in
there.

**Comment by fmontesi** [comment]
By the way, this works correctly in my own installation (it's got the extra newline). So I'm closing the issue for now.

Another side remark: trim@StringUtils gets rid of the spaces at the beginning and end of a string easily:

```
include "console.iol"
include "exec.iol"
include "string_utils.iol"

main
{
    exec@Exec( "pwd" )( currentDir );
    trim@StringUtils( string(currentDir) )( currentDir );
    moreFun = string(currentDir) + "addFun";
    println@Console( moreFun )()
}
```

**Comment by Ezbob** [comment]
Thanks all for your quick response! 
Though I code on Arch Linux, it was as @thesave said there was a newline attached + I was probably coding too late at night to notice. Using trim together with string cast solved it.
