### ISSUE TITLE
Deep Copy and Aliases in Inline Trees

### ISSUE THREAD

**Issue by fmontesi** [jolie/jolie#8]
Right now, the syntax for Inline Trees (ITs) supports only assignments, for example:

{ .x = 4, .y = 6 }

We should also support deep copies (allowing for nested ITs) and aliases (->), for example:

{ .x << { .z = 3, .i = 2 }, .y -> a }

**Comment by mwallnoefer** [comment]
Should have been fixed I think (1.8.0 or so).
