### ISSUE TITLE
Cannot copy jap-files.

### ISSUE THREAD

**Issue by Ezbob** [jolie/jolie#82]
I have this strange problem when copying a jap-file (Jolie jar-files).

When I copy the jap-file, using `readFile@File(...)(...)` on the jap-file and subsequently call `writeFile@File(...)(...)` with the contents of the read file operation, I cannot uncompress the newly copied jap-file as the tool informs me that a portion of the newly copied file is missing. This is not a problem when trying to uncompress the old jap-file.

I created a new extension `copyFile` which solves this and adds file copying as a new file operation to Jolie, but this is just a workaround. Any clues?

**Comment by fmontesi** [comment]
Can you post somewhere a super easy example that shows the bug? Are you using the binary format when calling File?

**Comment by Ezbob** [comment]
Ah.. I was not using the binary format. Using the binary format fixed it. Sorry about that.
 
I have created an extension for Jolie simply called `copy` that uses the `Files.copy(...)` from Java 7 to copy any file or directory. Could this be an interesting enhancement for the Jolie Standard liberary?

**Comment by fmontesi** [comment]
@Ezbob sure, can you show us the interface (types) of that operation?

**Comment by fmontesi** [comment]
I'm marking this as closed in the meantime, feel free to open a pull request for copy!
