### ISSUE TITLE
exec operation in Exec Service does not work

### ISSUE THREAD

**Issue by bmaschio** [jolie/jolie#83]
Hello there

We were trying in linux system to execute a simple ls using exec with the following code
'
   execRequest = "ls";
   execRequest.args[0] = "--file";
   execRequest.args[1] = "*.pdf";
   execRequest.workingDirectory= "./"; 
   execRequest.stdOutConsoleEnable = false;
   valueToPrettyString@StringUtils (execRequest)(s);
   println@Console("execRequest"+s)();

   exec@Exec(execRequest)(execResponse);
   valueToPrettyString@StringUtils (execResponse)(s);
   println@Console("execResponse"+s)()

'

I get this result

![image](https://cloud.githubusercontent.com/assets/12083716/15887556/31125184-2d63-11e6-9de5-a15210871536.png)

Am I getting something wronge

**Comment by Quiquex** [comment]
Hi, I encountered the same issue.
After some looking around I found that ProcessBuilder (wich is used in ExecService) cannot expand wildcards. 
But passing the commands to a shell should work.
I tested
```
execRequest = "bash -c";
execRequest.args[0] = "ls --file *.pdf"
```
and
```
execRequest = "cmd /c";
execRequest.args[0] = "dir";
execRequest.args[1] = "*.pdf";
```
both work as supposed.
