### ISSUE TITLE
Bug in jolie.xml.XmlUtils elementsToSubValuesForStoring

### ISSUE THREAD

**Issue by klag** [jolie/jolie#93]
when an empty string node is transformed into a xml and then transformed back in a jolie value, it becomes a void field. test case:

include "console.iol"
include "string_utils.iol"
include "xml_utils.iol"
include "file.iol"

main {
   f.filename = "text.xml";
   f.format = "xml_store";
   f.content.p.c = "";
   f.content.p.d = "ciao";
   writeFile@File( f )();

   undef( f.content );
   readFile@File( f )( content );
   valueToPrettyString@StringUtils( content )( s );
   println@Console( s )();
   if ( content.p.c instanceof void ) {
     println@Console( "FAULT" )()
   } else {
     println@Console("OK")()
   }
   ;
   req.rootNodeName = "root";
   req.root.p.c = "";
   req.root.p.d = "ciao";
   valueToXml@XmlUtils( req )( xml );
   xmlToValue@XmlUtils( xml )( res );
   valueToPrettyString@StringUtils( res )( s );
   println@Console( s )();

   if ( res.p.c instanceof void ) {
     println@Console( "FAULT" )()
   } else {
     println@Console("OK")()
   }

}

**Comment by fmontesi** [comment]
Fixed by #94
